"use client";

import {
  DndContext,
  DragEndEvent,
  PointerSensor,
  closestCorners,
  useDraggable,
  useDroppable,
  useSensor,
  useSensors,
} from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { FormEvent, KeyboardEvent, ReactNode, useEffect, useMemo, useState } from "react";
import "./buho-app.css";

type View = "dashboard" | "brands" | "matches" | "cases" | "notifications" | "users";
type BrandStatus = "En monitoreo" | "Sin monitoreo";
type MatchLevel = "Alta" | "Media" | "Baja";
type MatchStatus = "Pendiente" | "En observación" | "Descartada" | "Convertida en caso";
type CaseStage = "Preparación" | "Presentado" | "Seguimiento" | "Concluido";
type Brand = { id: string; name: string; owner: string; registration: string; classes: string; country: string; status: BrandStatus; matches: number; cases: number; updated: string; rut: string; inapiUrl: string; visual: string };
type Match = { id: string; brandId: string; brand: string; found: string; applicant: string; application: string; score: number; level: MatchLevel; status: MatchStatus; date: string; deadline?: string; source: string; owner: string; rut: string; applicantRut: string; officialUrl: string; brandRegistration?: string; officialRegistration?: string };
type LegalCase = { id: string; title: string; brand: string; client: string; stage: CaseStage; priority: MatchLevel; deadline: string; owner: string; sourceMatch?: string };
type DemoUser = { id: string; name: string; email: string; createdAt: string; initials: string };
type Notice = { id: string; title: string; brand: string; urgency: MatchLevel; status: "Pendiente" | "Gestionada"; date: string; subject: string; body: string; matchId?: string };
type DemoSnapshot = { brands: Brand[]; matches: Match[]; cases: LegalCase[]; users: DemoUser[]; notices: Notice[] };
type RutCandidate = { name: string; registration: string; classes: string; visual: string; inapiUrl: string; description: string };

const NAV: { id: View; label: string }[] = [
  { id: "dashboard", label: "Inicio" }, { id: "brands", label: "Marcas" }, { id: "matches", label: "Coincidencias" },
  { id: "cases", label: "Casos" }, { id: "notifications", label: "Notificaciones" }, { id: "users", label: "Usuarios" },
];
const INAPI_SEARCH_URL = "https://buscadormarcas.inapi.cl/Marca/BuscarMarca.aspx";
const COCA_COLA_RUT = "96.671.040-3";
const stages: CaseStage[] = ["Preparación", "Presentado", "Seguimiento", "Concluido"];

const coreBrands: Brand[] = [
  ["BM-018", "NOVA FOODS", "Grupo Nova SpA", "1428891", "29, 30, 35", "En monitoreo", "77.104.290-6", "NOVA"],
  ["BM-017", "TERRA SUR", "Terra Sur Limitada", "1413208", "33, 35", "En monitoreo", "76.991.842-1", "TERRA"],
  ["BM-016", "CASA NUBE", "Inmobiliaria Casa Nube", "1399480", "36, 37", "En monitoreo", "77.291.808-4", "CASA"],
  ["BM-015", "PULSO", "Pulso Salud SpA", "1377012", "05, 10, 44", "En monitoreo", "76.770.241-9", "PULSO"],
  ["BM-014", "LINARIA", "Laboratorios Linaria", "1351164", "03, 05", "Sin monitoreo", "77.034.518-2", "LINARIA"],
].map(([id, name, owner, registration, classes, status, rut, visual]): Brand => ({ id, name, owner, registration, classes, country: "Chile", status: status as BrandStatus, matches: name === "NOVA FOODS" ? 2 : name === "TERRA SUR" || name === "CASA NUBE" || name === "LINARIA" ? 1 : 0, cases: name === "PULSO" || name === "LINARIA" ? 0 : 1, updated: "19 ago 2026", rut, inapiUrl: INAPI_SEARCH_URL, visual }));
const supplementalNames = ["ALTURA", "BRISA PACÍFICO", "CÍRCULO", "DORADA", "ENLACE", "FARO SUR", "GRANO VIVO", "HORIZONTE", "ÍNDIGO", "JARDÍN NORTE", "KORA", "LUMEN", "MÁREA", "NEXO", "ORIGEN"];
const initialBrands: Brand[] = [...coreBrands, ...supplementalNames.map((name, index): Brand => ({ id: `BM-${100 + index}`, name, owner: `${name} Chile SpA`, registration: String(1502300 + index), classes: index % 2 ? "09, 35, 42" : "29, 30, 32", country: "Chile", status: index % 5 === 0 ? "Sin monitoreo" : "En monitoreo", matches: 0, cases: 0, updated: "18 ago 2026", rut: `77.${String(300000 + index * 921).padStart(6, "0")}-${index % 10}`, inapiUrl: INAPI_SEARCH_URL, visual: name.slice(0, 6) }))];

const initialMatches: Match[] = [
  { id: "CO-2481", brandId: "BM-018", brand: "NOVA FOODS", found: "NOVA FUDS", applicant: "Alimentos del Pacífico Ltda.", application: "1570234", score: 94, level: "Alta", status: "Pendiente", date: "19 ago 2026", deadline: "27 ago 2026", source: "Diario Oficial", owner: "José Ignacio Ibieta", rut: "77.104.290-6", applicantRut: "77.291.660-8", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2479", brandId: "BM-017", brand: "TERRA SUR", found: "TERRA DEL SUR", applicant: "Viñas del Valle SpA", application: "1570189", score: 87, level: "Alta", status: "Pendiente", date: "19 ago 2026", deadline: "29 ago 2026", source: "Diario Oficial", owner: "Matías Soto", rut: "76.991.842-1", applicantRut: "76.406.883-2", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2472", brandId: "BM-016", brand: "CASA NUBE", found: "CASANUBE", applicant: "Desarrollos Urbanos S.A.", application: "1569912", score: 73, level: "Media", status: "En observación", date: "18 ago 2026", source: "INAPI", owner: "José Ignacio Ibieta", rut: "77.291.808-4", applicantRut: "77.680.149-4", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2468", brandId: "BM-018", brand: "NOVA FOODS", found: "NOVO FOOD LAB", applicant: "Novo Lab Chile", application: "1569781", score: 66, level: "Media", status: "Pendiente", date: "18 ago 2026", source: "INAPI", owner: "Camila León", rut: "77.104.290-6", applicantRut: "77.333.809-7", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2451", brandId: "BM-014", brand: "LINARIA", found: "LINAR", applicant: "Cosmética Natural Chile", application: "1569114", score: 48, level: "Baja", status: "Descartada", date: "15 ago 2026", source: "Diario Oficial", owner: "Camila León", rut: "77.034.518-2", applicantRut: "76.890.471-2", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2485", brandId: "BM-018", brand: "NOVA FOODS", found: "NOVA NUTRA", applicant: "Nutra Chile SpA", application: "1570284", score: 91, level: "Alta", status: "Pendiente", date: "20 ago 2026", deadline: "31 ago 2026", source: "Diario Oficial", owner: "José Ignacio Ibieta", rut: "77.104.290-6", applicantRut: "77.492.180-1", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2483", brandId: "BM-017", brand: "TERRA SUR", found: "TIERRA SUR", applicant: "Tierra Sur Comercial SpA", application: "1570256", score: 79, level: "Media", status: "Pendiente", date: "20 ago 2026", source: "INAPI", owner: "Matías Soto", rut: "76.991.842-1", applicantRut: "77.486.321-4", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2476", brandId: "BM-016", brand: "CASA NUBE", found: "CASA NUBIA", applicant: "Nubia Desarrollos Ltda.", application: "1570117", score: 70, level: "Media", status: "Pendiente", date: "19 ago 2026", source: "Diario Oficial", owner: "Camila León", rut: "77.291.808-4", applicantRut: "77.441.902-7", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2463", brandId: "BM-015", brand: "PULSO", found: "PULSO VITAL", applicant: "Vital Salud S.A.", application: "1569564", score: 55, level: "Baja", status: "Pendiente", date: "18 ago 2026", source: "INAPI", owner: "José Ignacio Ibieta", rut: "76.770.241-9", applicantRut: "77.398.015-2", officialUrl: INAPI_SEARCH_URL },
  { id: "CO-2458", brandId: "BM-100", brand: "ALTURA", found: "ALTURIA", applicant: "Alturia Outdoor SpA", application: "1569372", score: 43, level: "Baja", status: "Pendiente", date: "17 ago 2026", source: "Diario Oficial", owner: "Matías Soto", rut: "77.300.000-0", applicantRut: "77.351.764-8", officialUrl: INAPI_SEARCH_URL },
];
const initialCases: LegalCase[] = [
  { id: "BM-1042", title: "Oposición Nova Fuds", brand: "NOVA FOODS", client: "Grupo Nova SpA", stage: "Preparación", priority: "Alta", deadline: "20 ago", owner: "José Ignacio Ibieta", sourceMatch: "CO-2481" },
  { id: "BM-1038", title: "Revisión Terra del Sur", brand: "TERRA SUR", client: "Terra Sur Limitada", stage: "Preparación", priority: "Alta", deadline: "22 ago", owner: "Matías Soto", sourceMatch: "CO-2479" },
  { id: "BM-1036", title: "Oposición CasaNube", brand: "CASA NUBE", client: "Inmobiliaria Casa Nube", stage: "Presentado", priority: "Media", deadline: "27 ago", owner: "Camila León", sourceMatch: "CO-2472" },
  { id: "BM-1027", title: "Seguimiento resolución Pulso", brand: "PULSO", client: "Pulso Salud SpA", stage: "Seguimiento", priority: "Baja", deadline: "11 sep", owner: "José Ignacio Ibieta" },
];
const initialUsers: DemoUser[] = [
  { id: "US-001", name: "José Ignacio Ibieta", email: "jose.ignacio@ibieta.cl", createdAt: "04 mar 2026", initials: "JI" }, { id: "US-002", name: "Matías Soto", email: "matias@estudio.cl", createdAt: "18 abr 2026", initials: "MS" }, { id: "US-003", name: "Camila León", email: "camila@estudio.cl", createdAt: "02 jun 2026", initials: "CL" }, { id: "US-004", name: "Victor Tirreau", email: "victor@ibieta.cl", createdAt: "22 ago 2026", initials: "VT" },
];
const initialNotices: Notice[] = [
  { id: "NO-114", title: "Coincidencia de alta similitud publicada en Diario Oficial", brand: "NOVA FOODS", urgency: "Alta", status: "Pendiente", date: "Hoy", matchId: "CO-2481", subject: "Alerta de marca: posible coincidencia con NOVA FOODS", body: "Hola,\n\nDetectamos una coincidencia de alta similitud publicada en el Diario Oficial para NOVA FOODS. Revisa la ficha para definir los próximos pasos.\n\nSaludos," },
  { id: "NO-112", title: "En 5 días vence el plazo para presentar una oposición", brand: "TERRA SUR", urgency: "Alta", status: "Pendiente", date: "Hoy", matchId: "CO-2479", subject: "Próximo plazo: coincidencia CO-2479", body: "Hola,\n\nEn 5 días vence el plazo para presentar una oposición respecto de la coincidencia CO-2479.\n\nSaludos," },
  { id: "NO-110", title: "Una coincidencia de media similitud que sigues se publicó en el Diario Oficial", brand: "CASA NUBE", urgency: "Media", status: "Pendiente", date: "Ayer", matchId: "CO-2472", subject: "Nueva publicación: coincidencia de media similitud para CASA NUBE", body: "Hola,\n\nLa coincidencia de media similitud CO-2472 asociada a CASA NUBE fue publicada en el Diario Oficial.\n\nSaludos," },
  { id: "NO-109", title: "Una coincidencia de baja similitud que sigues se publicó en el Diario Oficial", brand: "LINARIA", urgency: "Baja", status: "Pendiente", date: "15 ago", matchId: "CO-2451", subject: "Nueva publicación: coincidencia de baja similitud para LINARIA", body: "Hola,\n\nLa coincidencia de baja similitud CO-2451 asociada a LINARIA fue publicada en el Diario Oficial.\n\nSaludos," },
];
const cocaColaCatalogue: RutCandidate[] = [
  ["COCA-COLA", "1560201", "32, 33", "Coca-Cola · bebida", "Bebidas sin alcohol y preparados"], ["FANTA", "1560202", "32", "Fanta · naranja", "Bebidas saborizadas sin alcohol"], ["SPRITE", "1560203", "32", "Sprite · lima", "Bebidas gaseosas sin alcohol"], ["POWERADE", "1560204", "32", "Powerade · deporte", "Bebidas deportivas y energéticas"], ["MINUTE MAID", "1560205", "32", "Minute Maid · jugo", "Jugos, néctares y bebidas de fruta"], ["DEL VALLE", "1560206", "32", "Del Valle · fruta", "Jugos y bebidas de fruta"], ["AQUARIUS", "1560207", "32", "Aquarius · hidratación", "Bebidas saborizadas sin alcohol"], ["SCHWEPPES", "1560208", "32", "Schweppes · tónica", "Bebidas gaseosas y aguas tónicas"], ["TOPO CHICO", "1560209", "32", "Topo Chico · agua", "Aguas minerales y bebidas gaseosas"], ["FUZE TEA", "1560210", "30, 32", "Fuze Tea · té", "Tés listos para beber"],
].map(([name, registration, classes, visual, description]) => ({ name, registration, classes, visual, description, inapiUrl: INAPI_SEARCH_URL }));

function useDemoStorage<T>(key: string, initialValue: T, hydrate?: (value: T) => T) {
  const [value, setValue] = useState<T>(initialValue); const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = window.localStorage.getItem(key); if (saved) { const parsed = JSON.parse(saved) as T; setValue(hydrate ? hydrate(parsed) : parsed); } } catch { /* local fallback */ } setReady(true); }, 0); return () => window.clearTimeout(timer); }, [hydrate, key]);
  useEffect(() => { if (ready) window.localStorage.setItem(key, JSON.stringify(value)); }, [key, ready, value]);
  return [value, setValue] as const;
}
function Tone({ children, tone = "neutral" }: { children: ReactNode; tone?: string }) { return <span className={`buho-tone tone-${tone}`}>{children}</span>; }
function similarityLabel(level: MatchLevel) { return `${level} similitud`; }
function stageTone(stage: CaseStage) { return `stage-${stage.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")}`; }
function formatToday() { return new Intl.DateTimeFormat("es-CL", { timeZone: "America/Santiago", weekday: "long", day: "numeric", month: "short", year: "numeric" }).format(new Date()).toUpperCase().replaceAll(" DE ", " "); }
function normalizeBrand(brand: Brand): Brand { return { ...brand, status: String(brand.status) === "Pausada" || String(brand.status) === "Sin monitoreo" ? "Sin monitoreo" : "En monitoreo" }; }
function enrichedNotices(source: Notice[]) { const serverNotices = source.filter((notice) => notice.id !== "NO-108").map((notice) => { const curated = initialNotices.find((item) => item.id === notice.id); return curated ? { ...notice, ...curated, status: notice.status } : { ...notice, urgency: notice.urgency as MatchLevel, matchId: notice.matchId ?? (notice.title.includes("TERRA") ? "CO-2479" : notice.title.includes("CASA") ? "CO-2472" : notice.title.includes("NOVA") ? "CO-2481" : undefined) }; }); return [...serverNotices, ...initialNotices.filter((item) => !serverNotices.some((notice) => notice.id === item.id))]; }
function mergeInitialMatches(source: Match[]) { return [...source, ...initialMatches.filter((item) => !source.some((match) => match.id === item.id))]; }
function removeDeprecatedNotices(source: Notice[]) { return source.filter((notice) => notice.id !== "NO-108"); }
function normalizeCases(source: LegalCase[]) { return source.map((item) => ({ ...item, stage: String(item.stage) === "Evaluación" ? "Preparación" : item.stage } as LegalCase)); }

export default function BuhoAppPage() {
  const [view, setView] = useState<View>("dashboard");
  const [brands, setBrands] = useDemoStorage("buho-demo-v3-brands", initialBrands); const [matches, setMatches] = useDemoStorage("buho-demo-v4-matches", initialMatches, mergeInitialMatches); const [cases, setCases] = useDemoStorage("buho-demo-v3-cases", initialCases, normalizeCases); const [users, setUsers] = useDemoStorage("buho-demo-v3-users", initialUsers); const [notices, setNotices] = useDemoStorage("buho-demo-v4-notices", initialNotices, removeDeprecatedNotices);
  const [databaseReady, setDatabaseReady] = useState(false); const [brandFormOpen, setBrandFormOpen] = useState(false); const [rutDrawerOpen, setRutDrawerOpen] = useState(false); const [caseFormOpen, setCaseFormOpen] = useState(false); const [userFormOpen, setUserFormOpen] = useState(false); const [selectedBrand, setSelectedBrand] = useState<string | null>(null); const [selectedMatch, setSelectedMatch] = useState<string | null>(null); const [selectedCase, setSelectedCase] = useState<string | null>(null); const [selectedNotice, setSelectedNotice] = useState<string | null>(null); const [query, setQuery] = useState(""); const [levelFilter, setLevelFilter] = useState("Todas"); const [brandFilter, setBrandFilter] = useState("Todas"); const [matchBrandFilter, setMatchBrandFilter] = useState<string | null>(null); const [toast, setToast] = useState("");
  useEffect(() => { const syncHash = () => { const hash = window.location.hash.replace("#", "") as View; if (NAV.some((item) => item.id === hash)) setView(hash); }; syncHash(); window.addEventListener("hashchange", syncHash); return () => window.removeEventListener("hashchange", syncHash); }, []);
  // applySnapshot only closes over stable React setters; the initial fetch must run once.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let active = true; fetch("/api/demo", { cache: "no-store" }).then(async (response) => { if (!active || !response.ok) return; const payload = await response.json() as { data: DemoSnapshot }; applySnapshot(payload.data); setDatabaseReady(true); }).catch(() => { /* local mode remains available */ }); return () => { active = false; }; }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 2800); return () => window.clearTimeout(timer); }, [toast]);
  const selectedBrandData = brands.find((brand) => brand.id === selectedBrand); const selectedMatchData = matches.find((match) => match.id === selectedMatch); const selectedCaseData = cases.find((item) => item.id === selectedCase); const selectedNoticeData = notices.find((item) => item.id === selectedNotice);
  const filteredMatches = useMemo(() => matches.filter((match) => (levelFilter === "Todas" || match.level === levelFilter) && (!matchBrandFilter || match.brand === matchBrandFilter)).sort((a, b) => b.score - a.score), [levelFilter, matchBrandFilter, matches]);
  function applySnapshot(snapshot: DemoSnapshot) { setBrands(snapshot.brands.map(normalizeBrand)); setMatches(snapshot.matches); setCases(normalizeCases(snapshot.cases)); setUsers(snapshot.users); setNotices(enrichedNotices(snapshot.notices)); }
  function navigate(next: View) { setView(next); setQuery(""); window.history.pushState(null, "", `#${next}`); window.requestAnimationFrame(() => document.querySelector<HTMLElement>(".buho-workspace")?.scrollTo({ top: 0, behavior: "smooth" })); }
  async function requestAction(input: Record<string, unknown>, sync = true) { if (!databaseReady) return false; try { const response = await fetch("/api/demo", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); const payload = await response.json() as { data?: DemoSnapshot; message?: string }; if (!response.ok) throw new Error(payload.message || "No fue posible guardar el cambio"); if (sync && payload.data) applySnapshot(payload.data); return true; } catch (error) { setToast(error instanceof Error ? error.message : "No fue posible guardar el cambio"); return false; } }
  async function addBrand(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const input = { action: "createBrand", name: String(data.get("name")), owner: String(data.get("owner")), registration: String(data.get("registration")), classes: String(data.get("classes")), country: "Chile", description: String(data.get("description")), rut: String(data.get("rut")), inapiUrl: String(data.get("inapiUrl")), visual: String(data.get("visual")) }; if (databaseReady) { if (!await requestAction(input)) return; } else setBrands([{ id: `BM-${100 + brands.length}`, name: input.name, owner: input.owner, registration: input.registration, classes: input.classes, country: "Chile", status: "En monitoreo", matches: 0, cases: 0, updated: formatToday(), rut: input.rut, inapiUrl: input.inapiUrl, visual: input.visual }, ...brands]); setBrandFormOpen(false); setToast("Marca añadida desde la simulación INAPI"); navigate("brands"); }
  async function addRutBrands(selected: RutCandidate[]) { const slots = Math.max(0, 25 - brands.length); const allowed = selected.filter((candidate) => !brands.some((brand) => brand.name.toLowerCase() === candidate.name.toLowerCase())).slice(0, slots); if (!allowed.length) { setToast(slots ? "Estas marcas ya están en seguimiento" : "No quedan cupos en el plan Estudio"); return; } const batch = allowed.map((candidate) => ({ ...candidate, owner: "Coca-Cola de Chile S.A.", country: "Chile", rut: COCA_COLA_RUT })); if (databaseReady) { if (!await requestAction({ action: "bulkCreateBrands", brands: batch })) return; } else setBrands([...batch.map((candidate, index): Brand => ({ id: `BM-${200 + brands.length + index}`, name: candidate.name, owner: candidate.owner, registration: candidate.registration, classes: candidate.classes, country: candidate.country, status: "En monitoreo", matches: 0, cases: 0, updated: formatToday(), rut: candidate.rut, inapiUrl: candidate.inapiUrl, visual: candidate.visual })), ...brands]); setRutDrawerOpen(false); setBrandFilter("Todas"); setToast(`${allowed.length} marca${allowed.length === 1 ? "" : "s"} de Coca-Cola añadida${allowed.length === 1 ? "" : "s"} al seguimiento`); }
  async function addCase(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const input = { action: "createCase", title: String(data.get("title")), brand: String(data.get("brand")), client: String(data.get("client")), priority: String(data.get("priority")), deadline: String(data.get("deadline")), owner: String(data.get("owner")), description: String(data.get("description") || "") }; if (databaseReady) { if (!await requestAction(input)) return; } else setCases([{ id: `BM-${1043 + cases.length}`, title: input.title, brand: input.brand, client: input.client, stage: "Preparación", priority: input.priority as MatchLevel, deadline: input.deadline, owner: input.owner }, ...cases]); setCaseFormOpen(false); setToast("Caso creado correctamente"); }
  async function addUser(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get("name")); const email = String(data.get("email")); if (databaseReady) { if (!await requestAction({ action: "createUser", name, email })) return; } else setUsers([...users, { id: `US-${users.length + 1}`, name, email, createdAt: formatToday(), initials: name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase() }]); setUserFormOpen(false); setToast("Usuario agregado a la organización"); }
  async function reviewMatch(status: MatchStatus) { if (!selectedMatchData) return; if (databaseReady) { if (!await requestAction({ action: "reviewMatch", id: selectedMatchData.id, status })) return; } else setMatches((current) => current.map((match) => match.id === selectedMatchData.id ? { ...match, status } : match)); setToast(status === "Convertida en caso" ? "Coincidencia convertida en caso" : `Coincidencia marcada: ${status}`); setSelectedMatch(null); }
  async function moveCase(item: LegalCase, stage: CaseStage) { if (item.stage === stage) return; const priorCases = cases; setCases((current) => current.map((entry) => entry.id === item.id ? { ...entry, stage } : entry)); setToast(`${item.id} movido a ${stage}`); if (databaseReady && !await requestAction({ action: "moveCase", id: item.id, stage }, false)) setCases(priorCases); }
  async function unlinkCaseMatch(item: LegalCase) { if (!item.sourceMatch) return; const sourceMatch = item.sourceMatch; if (databaseReady) { if (!await requestAction({ action: "unlinkCaseMatch", id: item.id })) return; } else { setCases((current) => current.map((entry) => entry.id === item.id ? { ...entry, sourceMatch: undefined } : entry)); setMatches((current) => current.map((match) => match.id === sourceMatch ? { ...match, status: "Pendiente" } : match)); } setSelectedMatch(null); setToast(`${sourceMatch} fue sacada del caso ${item.id}`); }
  async function toggleBrandMonitoring(brand: Brand) { const nextStatus: BrandStatus = brand.status === "En monitoreo" ? "Sin monitoreo" : "En monitoreo"; const priorBrands = brands; setBrands((current) => current.map((item) => item.id === brand.id ? { ...item, status: nextStatus, updated: formatToday() } : item)); setToast(nextStatus === "En monitoreo" ? `${brand.name} volvió al monitoreo` : `${brand.name} quedó sin monitoreo`); if (databaseReady && !await requestAction({ action: "toggleBrandMonitoring", id: brand.id, enabled: nextStatus === "En monitoreo" }, false)) setBrands(priorBrands); }
  function updateNotice(id: string, patch: Partial<Notice>) { setNotices((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); if (databaseReady && !["NO-109", "NO-110"].includes(id)) void requestAction({ action: "updateNotice", id, ...patch }, false); }
  async function copyText(text: string, label: string) { try { await navigator.clipboard.writeText(text); setToast(`${label} copiado`); } catch { setToast("Selecciona el texto y cópialo manualmente"); } }
  const pageHeadings: Record<View, [string, string]> = { dashboard: ["Buenos días, José Ignacio.", "Resumen de tu cartera y acciones prioritarias"], brands: ["Marcas en seguimiento", "Administra la cartera activa de tu organización"], matches: ["Coincidencias", "Revisa y clasifica los hallazgos de tu cartera"], cases: ["Seguimiento de casos", "Gestiona cada causa sin perder el contexto original"], notifications: ["Centro de notificaciones", "Novedades y plazos de tu cartera"], users: ["Usuarios activos", "Personas con acceso a la organización"] };
  return <main className="buho-app">
    <aside className="buho-sidebar">
      <div aria-label="Buho Marc" className="buho-wordmark">BUHO MARC</div>
      <button className="buho-profile" type="button"><span>JI</span><div><strong>José Ignacio Ibieta</strong><small>Estudio Ibieta IP</small></div></button>
      <nav aria-label="Navegación de la aplicación">{NAV.map((item, index) => <button className={view === item.id ? "is-active" : ""} key={item.id} onClick={() => { setMatchBrandFilter(null); navigate(item.id); }} type="button"><span>0{index + 1}</span>{item.label}{item.id === "notifications" && notices.filter((notice) => notice.status === "Pendiente").length > 0 && <b>{notices.filter((notice) => notice.status === "Pendiente").length}</b>}</button>)}</nav>
      <div className="buho-plan"><span>PLAN ESTUDIO</span><strong>{brands.length} de 25 marcas</strong><i><b style={{ width: `${Math.min(100, brands.length / 25 * 100)}%` }} /></i><small>{Math.max(0, 25 - brands.length)} espacios disponibles</small><a href="https://buho-marc.vercel.app/Landing#pricing">Ver pricing</a></div>
    </aside>
    <section className="buho-workspace">
      <div className={`buho-workspace-content${view === "dashboard" ? "" : " is-compact"}`}>
        <header className="buho-topbar"><div><span className="buho-overline">{formatToday()}</span><h1>{pageHeadings[view][0]}</h1><p>{pageHeadings[view][1]}</p></div>{view === "brands" && <div className="buho-actions"><label className="buho-search"><span>BUSCAR</span><input aria-label="Buscar marcas" onChange={(event) => setQuery(event.target.value)} placeholder="Marca, RUT o titular" value={query} /></label><button className="buho-secondary" onClick={() => setRutDrawerOpen(true)} type="button">Agregar según RUT</button><button className="buho-primary" onClick={() => setBrandFormOpen(true)} type="button">Agregar marca <span>+</span></button></div>}</header>
        {view === "dashboard" && <Dashboard brands={brands} cases={cases} matches={matches} onMatch={setSelectedMatch} onNavigate={(next) => { setMatchBrandFilter(null); navigate(next); }} />}
        {view === "brands" && <BrandsView brands={brands} filter={brandFilter} onFilter={setBrandFilter} onOpenBrand={(brand) => setSelectedBrand(brand.id)} onToggleMonitoring={toggleBrandMonitoring} query={query} />}
        {view === "matches" && <MatchesView brand={matchBrandFilter} matches={filteredMatches} level={levelFilter} onClearBrand={() => setMatchBrandFilter(null)} onLevel={setLevelFilter} onSelect={setSelectedMatch} />}
        {view === "cases" && <CasesView cases={cases} onAdd={() => setCaseFormOpen(true)} onMove={moveCase} onSelect={setSelectedCase} />}
        {view === "notifications" && <NotificationsView notices={notices} onOpenMatch={setSelectedMatch} onSelect={setSelectedNotice} />}
        {view === "users" && <UsersView users={users} onAdd={() => setUserFormOpen(true)} />}
      </div>
    </section>
    {brandFormOpen && <BrandForm brandsCount={brands.length} onClose={() => setBrandFormOpen(false)} onSubmit={addBrand} />}{rutDrawerOpen && <RutBrandsDrawer brands={brands} onAdd={addRutBrands} onClose={() => setRutDrawerOpen(false)} />}{caseFormOpen && <CaseForm brands={brands} users={users} onClose={() => setCaseFormOpen(false)} onSubmit={addCase} />}{userFormOpen && <UserForm onClose={() => setUserFormOpen(false)} onSubmit={addUser} />}{selectedBrandData && <BrandDrawer brand={selectedBrandData} onClose={() => setSelectedBrand(null)} />}{selectedCaseData && <CaseDrawer item={selectedCaseData} onClose={() => setSelectedCase(null)} onMove={(stage) => moveCase(selectedCaseData, stage)} onOpenMatch={(id) => setSelectedMatch(id)} onUnlink={() => void unlinkCaseMatch(selectedCaseData)} />}{selectedMatchData && <MatchDrawer match={selectedMatchData} onClose={() => setSelectedMatch(null)} onReview={reviewMatch} />}{selectedNoticeData && <NoticeDrawer notice={selectedNoticeData} onChange={(patch) => updateNotice(selectedNoticeData.id, patch)} onClose={() => setSelectedNotice(null)} onCopy={copyText} />}{toast && <div className="buho-toast" role="status"><span />{toast}</div>}
  </main>;
}

function Dashboard({ brands, cases, matches, onMatch, onNavigate }: { brands: Brand[]; cases: LegalCase[]; matches: Match[]; onMatch: (id: string) => void; onNavigate: (view: View) => void }) {
  const pendingMatches = matches.filter((item) => item.status === "Pendiente");
  const counts = { Alta: pendingMatches.filter((item) => item.level === "Alta").length, Media: pendingMatches.filter((item) => item.level === "Media").length, Baja: pendingMatches.filter((item) => item.level === "Baja").length };
  return <section className="buho-dashboard">
    <button className="buho-attention" onClick={() => onNavigate("matches")} type="button"><strong className="buho-attention-copy">{pendingMatches.length} coincidencias requieren ser revisadas</strong><span className="buho-attention-levels"><span className="is-high"><b>{counts.Alta}</b><small>Alta similitud</small></span><span className="is-medium"><b>{counts.Media}</b><small>Media similitud</small></span><span className="is-low"><b>{counts.Baja}</b><small>Baja similitud</small></span></span><strong>Revisar ahora →</strong></button>
    <section className="buho-metrics"><button onClick={() => onNavigate("brands")} type="button"><span>MARCAS EN SEGUIMIENTO</span><strong>{String(brands.length).padStart(2, "0")}</strong><small>{brands.length} de 25 cupos utilizados</small></button><button onClick={() => onNavigate("matches")} type="button"><span>NUEVAS COINCIDENCIAS</span><strong>{String(pendingMatches.length).padStart(2, "0")}</strong><small>Pendientes de revisión</small></button><button onClick={() => onNavigate("cases")} type="button"><span>CASOS ACTIVOS</span><strong>{String(cases.filter((item) => item.stage !== "Concluido").length).padStart(2, "0")}</strong><small>{cases.filter((item) => item.priority === "Alta" && item.stage !== "Concluido").length} con plazo cercano</small></button><button onClick={() => onNavigate("cases")} type="button"><span>OPOSICIONES EN CURSO</span><strong>{String(cases.filter((item) => item.title.includes("Oposición") && item.stage !== "Concluido").length).padStart(2, "0")}</strong><small>Revisa los próximos vencimientos</small></button></section>
    <section className="buho-dashboard-grid"><FullCalendar cases={cases} matches={matches} onMatch={onMatch} /><article className="buho-panel buho-dashboard-matches"><header><div><span className="buho-overline">BANDEJA DE REVISIÓN</span><h2>Coincidencias nuevas</h2></div><button onClick={() => onNavigate("matches")} type="button">Ver todas</button></header>{pendingMatches.slice(0, 3).map((match) => <button aria-label={`Abrir coincidencia ${match.id}`} className="buho-match-row" key={match.id} onClick={() => onMatch(match.id)} type="button"><Tone tone={match.level.toLowerCase()}>{similarityLabel(match.level)}</Tone><span><small>MARCA EN SEGUIMIENTO</small><b>{match.brand}</b></span><span><small>POSIBLE COINCIDENCIA</small><b>{match.found}</b></span></button>)}</article></section>
  </section>;
}
function FullCalendar({ cases, matches, onMatch }: { cases: LegalCase[]; matches: Match[]; onMatch: (id: string) => void }) {
  const [cursor, setCursor] = useState(() => new Date(2026, 7, 1));
  const calendarEvents = [
    { date: "2026-07-30", copy: "Revisión previa de antecedentes para TERRA DEL SUR.", match: "CO-2479", level: "Media" as MatchLevel },
    { date: "2026-08-20", copy: "Vence el plazo de NOVA FUDS para presentar una oposición.", match: "CO-2481", level: "Alta" as MatchLevel },
    { date: "2026-08-22", copy: "Vence el plazo de TERRA DEL SUR para presentar una oposición.", match: "CO-2479", level: "Alta" as MatchLevel },
    { date: "2026-08-24", copy: "La coincidencia de media similitud NOVO FOOD LAB fue publicada en Diario Oficial.", match: "CO-2468", level: "Media" as MatchLevel },
    { date: "2026-08-27", copy: "Vence el plazo de CASANUBE para presentar una oposición.", match: "CO-2472", level: "Media" as MatchLevel },
    { date: "2026-08-29", copy: "Último recordatorio de revisión para TERRA DEL SUR.", match: "CO-2479", level: "Alta" as MatchLevel },
    { date: "2026-09-02", copy: "Revisión de la publicación de PULSO VITAL.", match: "CO-2463", level: "Baja" as MatchLevel },
  ];
  const year = cursor.getFullYear(); const month = cursor.getMonth(); const monthKey = `${year}-${String(month + 1).padStart(2, "0")}`;
  const monthEvents = calendarEvents.filter((event) => event.date.startsWith(monthKey)); const days = new Date(year, month + 1, 0).getDate(); const firstDayOffset = (new Date(year, month, 1).getDay() + 6) % 7;
  const monthName = new Intl.DateTimeFormat("es-CL", { month: "long", year: "numeric" }).format(cursor).replace(/^./, (letter) => letter.toUpperCase());
  const shiftMonth = (amount: number) => setCursor((current) => new Date(current.getFullYear(), current.getMonth() + amount, 1));
  const caseCount = cases.filter((item) => item.title.includes("Oposición") && item.stage !== "Concluido").length;
  return <aside className="buho-panel buho-agenda"><header><div className="buho-calendar-heading"><div className="buho-calendar-meta"><span className="buho-overline">AGENDA LEGAL</span><small>{caseCount} oposiciones activas</small></div><div className="buho-calendar-navigation"><button aria-label="Mes anterior" onClick={() => shiftMonth(-1)} type="button">←</button><h2>{monthName}</h2><button aria-label="Mes siguiente" onClick={() => shiftMonth(1)} type="button">→</button></div></div></header><div className="buho-calendar-week"><span>LU</span><span>MA</span><span>MI</span><span>JU</span><span>VI</span><span>SA</span><span>DO</span></div><div className="buho-calendar-grid">{Array.from({ length: firstDayOffset }, (_, index) => <span aria-hidden="true" className="is-empty" key={`empty-${index}`} />)}{Array.from({ length: days }, (_, index) => { const day = index + 1; const event = monthEvents.find((item) => Number(item.date.slice(-2)) === day); return event ? <button aria-label={`${day} de ${monthName}: ${event.copy}`} className="is-event" data-tooltip={event.copy} key={day} onClick={() => onMatch(event.match)} title={event.copy} type="button">{day}</button> : <span key={day}>{day}</span>; })}</div><div className="buho-calendar-events">{monthEvents.length ? monthEvents.map((event) => <button key={event.date} onClick={() => onMatch(event.match)} type="button"><span>{event.date.slice(-2)} {monthName.slice(0, 3).toUpperCase()}</span><Tone tone={event.level.toLowerCase()}>{similarityLabel(event.level)}</Tone><strong>{event.copy}</strong></button>) : <p>No hay vencimientos registrados para este mes.</p>}</div><small className="buho-calendar-note">{matches.length} coincidencias registradas en la demo.</small></aside>;
}
function BrandsView({ brands, filter, onFilter, onOpenBrand, onToggleMonitoring, query }: { brands: Brand[]; filter: string; onFilter: (filter: string) => void; onOpenBrand: (brand: Brand) => void; onToggleMonitoring: (brand: Brand) => void; query: string }) {
  const [statusMenu, setStatusMenu] = useState<string | null>(null);
  const visible = [...brands.filter((brand) => (filter === "Todas" || brand.status === filter) && `${brand.name} ${brand.owner} ${brand.rut}`.toLowerCase().includes(query.toLowerCase()))].sort((a, b) => b.matches - a.matches || a.name.localeCompare(b.name, "es"));
  const monitored = brands.filter((item) => item.status === "En monitoreo").length;
  const openBrand = (brand: Brand) => onOpenBrand(brand);
  const onBrandKeyDown = (event: KeyboardEvent<HTMLTableRowElement>, brand: Brand) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openBrand(brand); } };
  return <section className="buho-view-brands"><section className="buho-quota"><div><span className="buho-overline">USO DEL PLAN</span><strong>{brands.length} de 25 marcas</strong><small>{Math.max(0, 25 - brands.length)} espacios disponibles</small></div><i><b style={{ width: `${Math.min(100, brands.length / 25 * 100)}%` }} /></i><a href="https://buho-marc.vercel.app/Landing#pricing">Ver pricing ↗</a></section><section className="buho-table-panel"><header><div className="buho-tabs"><button className={filter === "Todas" ? "is-active" : ""} onClick={() => onFilter("Todas")} type="button">Todas <b>{brands.length}</b></button><button className={filter === "En monitoreo" ? "is-active" : ""} onClick={() => onFilter("En monitoreo")} type="button">En monitoreo <b>{monitored}</b></button><button className={filter === "Sin monitoreo" ? "is-active" : ""} onClick={() => onFilter("Sin monitoreo")} type="button">Sin monitoreo <b>{brands.length - monitored}</b></button></div></header><div className="buho-table-wrap"><table><thead><tr><th>RUT</th><th>Marca</th><th>Titular</th><th>Clases de Niza</th><th>Estado</th><th>Inicio de seguimiento</th><th>Coincidencias</th></tr></thead><tbody>{visible.map((brand) => <tr aria-label={`Revisar ${brand.name}`} className="is-clickable" key={brand.id} onClick={() => openBrand(brand)} onKeyDown={(event) => onBrandKeyDown(event, brand)} role="button" tabIndex={0}><td>{brand.rut}</td><td><strong>{brand.name}</strong><small>{brand.id} · Reg. {brand.registration}</small></td><td>{brand.owner}</td><td>{brand.classes}</td><td><div className="buho-status-cell"><button aria-expanded={statusMenu === brand.id} className={`buho-status-trigger ${brand.status === "En monitoreo" ? "is-active" : "is-off"}`} onClick={(event) => { event.stopPropagation(); setStatusMenu((current) => current === brand.id ? null : brand.id); }} type="button">{brand.status} <span>⌄</span></button>{statusMenu === brand.id && <div className="buho-status-popover"><button onClick={(event) => { event.stopPropagation(); onToggleMonitoring(brand); setStatusMenu(null); }} type="button">{brand.status === "En monitoreo" ? "Dejar de monitorear" : "Empezar a monitorear"}</button></div>}</div></td><td>{brand.updated}</td><td><button aria-label={`Ver coincidencias de ${brand.name}`} className="buho-count-button" onClick={(event) => { event.stopPropagation(); openBrand(brand); }} type="button">{brand.matches}</button></td></tr>)}</tbody></table></div></section></section>;
}
function MatchesView({ brand, matches, level, onClearBrand, onLevel, onSelect }: { brand: string | null; matches: Match[]; level: string; onClearBrand: () => void; onLevel: (level: string) => void; onSelect: (id: string) => void }) { return <section className="buho-view-matches"><div className="buho-filter-row"><div className="buho-tabs">{["Todas", "Alta", "Media", "Baja"].map((item) => <button className={level === item ? "is-active" : ""} key={item} onClick={() => onLevel(item)} type="button">{item === "Todas" ? item : similarityLabel(item as MatchLevel)}{item !== "Todas" && <Tone tone={item.toLowerCase()}>{matches.filter((match) => match.level === item).length}</Tone>}</button>)}{brand && <button className="buho-brand-scope" onClick={onClearBrand} type="button">Marca: {brand} ×</button>}</div><small>Ordenadas de coincidencia mayor a menor</small></div><section className="buho-table-panel"><div className="buho-table-wrap"><table className="buho-matches-table"><thead><tr><th>Similitud</th><th>Estado</th><th>Marca en seguimiento</th><th>Marca con posible coincidencia</th><th>RUT solicitante</th><th>Solicitante</th><th>Publicado en Diario Oficial</th></tr></thead><tbody>{matches.map((match) => <tr aria-label={`Revisar coincidencia ${match.id}`} className="is-clickable" key={match.id} onClick={() => onSelect(match.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(match.id); } }} role="button" tabIndex={0}><td><Tone tone={match.level.toLowerCase()}>{similarityLabel(match.level)}</Tone></td><td><Tone tone={`match-${match.status.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replaceAll(" ", "-")}`}>{match.status}</Tone></td><td><strong>{match.brand}</strong><small>{match.brandId}</small></td><td><strong>{match.found}</strong><small>Solicitud {match.application}</small></td><td>{match.applicantRut}</td><td>{match.applicant}</td><td>{match.source === "Diario Oficial" ? match.date : "Pendiente de publicación"}</td></tr>)}</tbody></table></div></section></section>; }
function CasesView({ cases, onAdd, onMove, onSelect }: { cases: LegalCase[]; onAdd: () => void; onMove: (item: LegalCase, stage: CaseStage) => void; onSelect: (id: string) => void }) { const [mode, setMode] = useState<"board" | "list">("board"); const [ownerFilter, setOwnerFilter] = useState("Todos"); const [priorityFilter, setPriorityFilter] = useState("Todas"); const owners = ["Todos", ...Array.from(new Set(cases.map((item) => item.owner)))]; const priorities = ["Todas", "Alta", "Media", "Baja"]; const nextChoice = (current: string, choices: string[]) => choices[(choices.indexOf(current) + 1) % choices.length]; const visible = cases.filter((item) => (ownerFilter === "Todos" || item.owner === ownerFilter) && (priorityFilter === "Todas" || item.priority === priorityFilter)); return <section className="buho-view-cases"><div className="buho-board-toolbar"><div className="buho-tabs"><button className={mode === "board" ? "is-active" : ""} onClick={() => setMode("board")} type="button">Tablero</button><button className={mode === "list" ? "is-active" : ""} onClick={() => setMode("list")} type="button">Lista</button></div><div><button aria-label="Filtrar responsable" onClick={() => setOwnerFilter(nextChoice(ownerFilter, owners))} type="button">Responsable: {ownerFilter === "Todos" ? "Todos" : ownerFilter.split(" ")[0]}</button><button aria-label="Filtrar prioridad" onClick={() => setPriorityFilter(nextChoice(priorityFilter, priorities))} type="button">Prioridad: {priorityFilter}</button><button className="buho-secondary" onClick={onAdd} type="button">Nuevo caso</button></div></div>{mode === "list" ? <CaseList cases={visible} onSelect={onSelect} /> : <CaseBoard cases={visible} onMove={onMove} onSelect={onSelect} />}</section>; }
function CaseList({ cases, onSelect }: { cases: LegalCase[]; onSelect: (id: string) => void }) { return <section className="buho-table-panel"><div className="buho-table-wrap"><table><thead><tr><th>Caso</th><th>Marca</th><th>Etapa</th><th>Responsable</th><th>Próximo plazo</th><th /></tr></thead><tbody>{cases.map((item) => <tr className="is-clickable" key={item.id} onClick={() => onSelect(item.id)}><td><strong>{item.title}</strong><small>{item.id}</small></td><td>{item.brand}</td><td><Tone tone={stageTone(item.stage)}>{item.stage}</Tone></td><td>{item.owner}</td><td>{item.deadline}</td><td><button className="buho-row-arrow" type="button">Abrir →</button></td></tr>)}</tbody></table></div></section>; }
function CaseBoard({ cases, onMove, onSelect }: { cases: LegalCase[]; onMove: (item: LegalCase, stage: CaseStage) => void; onSelect: (id: string) => void }) { const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } })); function onDragEnd(event: DragEndEvent) { const nextStage = event.over?.id as CaseStage | undefined; const item = cases.find((candidate) => candidate.id === event.active.id); if (item && nextStage && stages.includes(nextStage)) onMove(item, nextStage); } return <DndContext collisionDetection={closestCorners} onDragEnd={onDragEnd} sensors={sensors}><section className="buho-kanban">{stages.map((stage) => <CaseColumn items={cases.filter((item) => item.stage === stage)} key={stage} onSelect={onSelect} stage={stage} />)}</section></DndContext>; }
function CaseColumn({ items, onSelect, stage }: { items: LegalCase[]; onSelect: (id: string) => void; stage: CaseStage }) { const { isOver, setNodeRef } = useDroppable({ id: stage }); return <section className={`buho-kanban-column ${isOver ? "is-over" : ""}`} ref={setNodeRef}><header><span>{stage}</span><b>{items.length}</b></header><div>{items.map((item) => <DraggableCaseCard item={item} key={item.id} onSelect={onSelect} />)}</div><p className="buho-drop-copy">Suelta aquí para mover</p></section>; }
function DraggableCaseCard({ item, onSelect }: { item: LegalCase; onSelect: (id: string) => void }) { const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: item.id }); return <article className={isDragging ? "is-dragging" : ""} ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform) }}><button aria-label={`Arrastrar o abrir ${item.title}`} className="buho-case-main" onClick={() => onSelect(item.id)} type="button" {...attributes} {...listeners}><div><Tone tone={item.priority.toLowerCase()}>{item.priority}</Tone><small>{item.id}</small></div><h3>{item.title}</h3><p>{item.brand} · {item.client}</p></button></article>; }
function NotificationsView({ notices, onSelect, onOpenMatch }: { notices: Notice[]; onSelect: (id: string) => void; onOpenMatch: (id: string) => void }) { return <section className="buho-view-notifications"><section className="buho-notice-list"><header><div className="buho-tabs"><button className="is-active" type="button">Todas <b>{notices.length}</b></button></div></header>{notices.map((notice) => <article key={notice.id}><button onClick={() => onSelect(notice.id)} type="button"><span className={`buho-notice-dot ${notice.status === "Pendiente" ? "is-new" : ""}`} /><div><span className="buho-overline">{notice.date} · {notice.brand}</span><strong>{notice.title}</strong><small>{notice.status === "Pendiente" ? "Novedad pendiente de revisión" : "Comunicación gestionada"}</small></div><Tone tone={notice.urgency.toLowerCase()}>{similarityLabel(notice.urgency)}</Tone></button>{notice.matchId && <button className="buho-notice-match-link" onClick={() => onOpenMatch(notice.matchId!)} type="button">Ver coincidencia →</button>}</article>)}</section></section>; }
function UsersView({ users, onAdd }: { users: DemoUser[]; onAdd: () => void }) { return <section className="buho-view-users buho-users"><header><div><span className="buho-overline">ORGANIZACIÓN</span><h2>Estudio Ibieta IP</h2></div><button className="buho-secondary" onClick={onAdd} type="button">Agregar usuario</button></header><div className="buho-user-list">{users.map((user) => <article key={user.id}><span>{user.initials}</span><div><strong>{user.name}</strong><small>{user.email}</small></div><div><small>FECHA DE CREACIÓN</small><strong>{user.createdAt}</strong></div></article>)}</div><p className="buho-info-line"><span>i</span>Todos los usuarios tienen acceso completo a la organización.</p></section>; }
function DrawerShell({ title, eyebrow, onClose, children, wide = false }: { title: string; eyebrow: string; onClose: () => void; children: ReactNode; wide?: boolean }) { return <div className="buho-overlay" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><aside aria-label={title} aria-modal="true" className={`buho-drawer ${wide ? "is-wide" : ""}`} role="dialog"><header><div><span className="buho-overline">{eyebrow}</span><h2>{title}</h2></div><button aria-label="Cerrar" onClick={onClose} type="button">×</button></header>{children}</aside></div>; }
function BrandForm({ onClose, onSubmit, brandsCount }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; brandsCount: number }) {
  const [registration, setRegistration] = useState(""); const [searched, setSearched] = useState(false);
  const found = searched && registration.trim().length > 0;
  const result = { name: "ACME ANDES", owner: "ACME Chile SpA", registration: registration.trim(), classes: "35, 42", rut: "77.888.410-5", visual: "ACME · denominativa", description: "Servicios comerciales, tecnológicos y de consultoría." };
  return <DrawerShell eyebrow="NUEVA MARCA" onClose={onClose} title="Agregar marca"><form className="buho-form" onSubmit={onSubmit}><label>N.º de registro<div className="buho-registration-search"><input aria-label="Número de registro" inputMode="numeric" onChange={(event) => { setRegistration(event.target.value); setSearched(false); }} placeholder="Ej. 1560998" required value={registration} /><button className="buho-secondary" disabled={!registration.trim()} onClick={() => setSearched(true)} type="button">Buscar</button></div></label><input name="inapiUrl" type="hidden" value={INAPI_SEARCH_URL} /><p className="buho-import-note">La búsqueda es una simulación para esta demo. Al consultar el registro se cargarán parámetros ficticios de INAPI.</p>{found && <article className="buho-import-result"><span className="buho-overline">FICHA ENCONTRADA · DEMO</span><dl><div><dt>RUT</dt><dd>{result.rut}</dd></div><div><dt>Marca</dt><dd>{result.name}</dd></div><div><dt>Titular</dt><dd>{result.owner}</dd></div><div><dt>Clases de Niza</dt><dd>{result.classes}</dd></div><div><dt>Estado</dt><dd>En monitoreo</dd></div></dl><input name="name" type="hidden" value={result.name} /><input name="owner" type="hidden" value={result.owner} /><input name="registration" type="hidden" value={result.registration} /><input name="classes" type="hidden" value={result.classes} /><input name="rut" type="hidden" value={result.rut} /><input name="visual" type="hidden" value={result.visual} /><input name="description" type="hidden" value={result.description} /></article>}<p className="buho-capacity">Usarás el espacio {brandsCount + 1} de 25 incluido en el plan Estudio.</p><footer><button onClick={onClose} type="button">Cancelar</button><button className="buho-primary" disabled={!found} type="submit">Agregar al seguimiento <span>→</span></button></footer></form></DrawerShell>;
}
function RutBrandsDrawer({ brands, onAdd, onClose }: { brands: Brand[]; onAdd: (selected: RutCandidate[]) => void; onClose: () => void }) { const [rut, setRut] = useState(""); const [searched, setSearched] = useState(false); const [selected, setSelected] = useState<string[]>([]); const slots = Math.max(0, 25 - brands.length); const toggle = (name: string) => setSelected((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]); const usable = cocaColaCatalogue.filter((candidate) => !brands.some((brand) => brand.name.toLowerCase() === candidate.name.toLowerCase())); return <DrawerShell eyebrow="IMPORTACIÓN DEMO" onClose={onClose} title="Agregar marcas según RUT" wide><div className="buho-drawer-scroll"><p className="buho-rut-intro">Ingresa cualquier RUT. Para esta demo se mostrará la cartera ficticia de Coca-Cola de Chile S.A. y podrás elegir qué marcas seguir.</p><div className="buho-rut-search"><input aria-label="RUT para buscar cartera" onChange={(event) => setRut(event.target.value)} placeholder="Ej. 96.671.040-3" value={rut} /><button className="buho-primary" onClick={() => setSearched(Boolean(rut.trim()))} type="button">Buscar <span>→</span></button></div>{searched && <><div className="buho-rut-result-head"><div><span className="buho-overline">TITULAR ENCONTRADO · DEMO</span><h3>Coca-Cola de Chile S.A.</h3><small>RUT {COCA_COLA_RUT} · {usable.length} marcas disponibles</small></div><span>{slots} cupos disponibles</span></div><div className="buho-rut-table"><table><thead><tr><th>Seguir</th><th>Marca</th><th>Link a INAPI</th><th>Visuales</th><th>Clases de Niza</th></tr></thead><tbody>{cocaColaCatalogue.map((candidate) => { const already = !usable.some((item) => item.name === candidate.name); const checked = selected.includes(candidate.name); return <tr key={candidate.name}><td><input aria-label={`Seguir ${candidate.name}`} checked={checked} disabled={already || (!checked && selected.length >= slots)} onChange={() => toggle(candidate.name)} type="checkbox" /></td><td><strong>{candidate.name}</strong><small>Reg. demo {candidate.registration}</small>{already && <em>Ya en seguimiento</em>}</td><td><a className="buho-inapi-link" href={candidate.inapiUrl} rel="noreferrer" target="_blank">Ver en INAPI ↗</a></td><td><span className="buho-visual-tile">{candidate.visual}</span><small>{candidate.description}</small></td><td>{candidate.classes}</td></tr>; })}</tbody></table></div></>}</div><footer className="buho-drawer-actions"><button onClick={onClose} type="button">Cancelar</button><button className="buho-primary" disabled={!selected.length} onClick={() => onAdd(cocaColaCatalogue.filter((candidate) => selected.includes(candidate.name)))} type="button">Agregar {selected.length || ""} marca{selected.length === 1 ? "" : "s"} <span>→</span></button></footer></DrawerShell>; }
function CaseForm({ brands, users, onClose, onSubmit }: { brands: Brand[]; users: DemoUser[]; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <DrawerShell eyebrow="NUEVO CASO" onClose={onClose} title="Crear caso"><form className="buho-form" onSubmit={onSubmit}><label>Título del caso<input name="title" placeholder="Ej. Oposición signo similar" required /></label><label>Marca relacionada<select name="brand">{brands.map((item) => <option key={item.id}>{item.name}</option>)}</select></label><label>Cliente<input name="client" placeholder="Organización propietaria" required /></label><div className="buho-form-grid"><label>Prioridad<select defaultValue="Media" name="priority"><option>Alta</option><option>Media</option><option>Baja</option></select></label><label>Próximo plazo<input name="deadline" placeholder="Ej. 30 ago" required /></label></div><label>Responsable<select name="owner">{users.map((user) => <option key={user.id}>{user.name}</option>)}</select></label><label>Descripción<textarea name="description" placeholder="Contexto y próximos pasos" rows={5} /></label><footer><button onClick={onClose} type="button">Cancelar</button><button className="buho-primary" type="submit">Crear caso <span>→</span></button></footer></form></DrawerShell>; }
function UserForm({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <DrawerShell eyebrow="ORGANIZACIÓN" onClose={onClose} title="Agregar usuario"><form className="buho-form" onSubmit={onSubmit}><label>Nombre completo<input name="name" placeholder="Nombre y apellido" required /></label><label>Correo electrónico<input name="email" placeholder="nombre@estudio.cl" required type="email" /></label><footer><button onClick={onClose} type="button">Cancelar</button><button className="buho-primary" type="submit">Agregar usuario <span>→</span></button></footer></form></DrawerShell>; }
function BrandDrawer({ brand, onClose }: { brand: Brand; onClose: () => void }) { return <DrawerShell eyebrow={`${brand.id} · FICHA DE MARCA`} onClose={onClose} title={brand.name}><div className="buho-drawer-scroll"><section className="buho-case-hero"><Tone tone={brand.status === "En monitoreo" ? "active" : "low"}>{brand.status}</Tone><h3>{brand.name}</h3><p>{brand.owner}</p></section><section className="buho-detail-grid"><div><span>RUT</span><strong>{brand.rut}</strong></div><div><span>N.º de registro</span><strong>{brand.registration}</strong></div><div><span>Titular</span><strong>{brand.owner}</strong></div><div><span>Clases de Niza</span><strong>{brand.classes}</strong></div><div><span>Estado</span><strong>{brand.status}</strong></div><div><span>Inicio de seguimiento</span><strong>{brand.updated}</strong></div></section><section className="buho-case-section"><header><h3>Registro INAPI</h3></header><a className="buho-inapi-link" href={brand.inapiUrl || INAPI_SEARCH_URL} rel="noreferrer" target="_blank">Ver en INAPI ↗</a></section></div><footer className="buho-drawer-actions"><button onClick={onClose} type="button">Cerrar</button></footer></DrawerShell>; }
function MatchDrawer({ match, onClose, onReview }: { match: Match; onClose: () => void; onReview: (status: MatchStatus) => void }) {
  const classes = "29, 30, 35"; const leftRegistration = match.brandRegistration ?? initialBrands.find((brand) => brand.id === match.brandId)?.registration ?? "Sin registro"; const officialRegistration = match.officialRegistration ?? `DO-${match.application}`;
  const comparisonRows = (side: "brand" | "found") => [{ label: "Visual", value: side === "brand" ? "Denominativa y logotipo" : "Signo denominativo" }, { label: "Fonético", value: side === "brand" ? match.brand : match.found }, { label: "Conceptual", value: "Alimentos y servicios relacionados" }, { label: "RUT", value: side === "brand" ? match.rut : match.applicantRut }, { label: "N.º registro (DO)", value: side === "brand" ? leftRegistration : officialRegistration }, { label: "N.º solicitud (INAPI)", value: side === "brand" ? "—" : match.application }, { label: "Clases de Niza", value: classes }];
  return <DrawerShell eyebrow={`${match.id} · ${match.source}`} onClose={onClose} title="Revisión de coincidencia" wide><div className="buho-drawer-scroll buho-drawer-match"><div className="buho-match-summary"><Tone tone={match.level.toLowerCase()}>{similarityLabel(match.level)}</Tone><div><strong>{similarityLabel(match.level)}</strong><small>{match.status} · {match.date}</small></div><a className="buho-inapi-link" href={match.officialUrl || INAPI_SEARCH_URL} rel="noreferrer" target="_blank">Ver en INAPI ↗</a></div><div className="buho-side-by-side"><article><span>MARCA EN SEGUIMIENTO</span><div className="buho-mark-card">{match.brand}</div><dl>{comparisonRows("brand").map((row) => <div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl></article><i>↔</i><article><span>MARCA CON POSIBLE COINCIDENCIA</span><div className="buho-mark-card is-found">{match.found}</div><dl>{comparisonRows("found").map((row) => <div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl></article></div><section className="buho-explanation"><span className="buho-overline">POR QUÉ SE DETECTÓ</span><p>El signo encontrado comparte la estructura denominativa principal y coincide en clases relacionadas. Esta explicación corresponde a datos ficticios de la demo; el motor real aún no está conectado.</p></section></div><footer className="buho-drawer-actions buho-review-actions"><button onClick={() => onReview("Descartada")} type="button">Descartar por ahora</button><button onClick={() => onReview("En observación")} type="button">Mantener en observación</button><button onClick={() => onReview("Convertida en caso")} type="button">Convertir en caso</button></footer></DrawerShell>;
}
function CaseDrawer({ item, onClose, onMove, onOpenMatch, onUnlink }: { item: LegalCase; onClose: () => void; onMove: (stage: CaseStage) => void; onOpenMatch: (id: string) => void; onUnlink: () => void }) {
  const [confirmingUnlink, setConfirmingUnlink] = useState(false);
  const nextStage = stages[stages.indexOf(item.stage) + 1];
  return <DrawerShell eyebrow={item.id} onClose={onClose} title={item.title}><div className="buho-drawer-scroll"><div className="buho-case-hero"><Tone tone={item.priority.toLowerCase()}>{item.priority}</Tone><Tone tone={stageTone(item.stage)}>{item.stage}</Tone><h3>{item.brand}</h3><p>{item.client}</p></div><section className="buho-detail-grid"><div><span>Responsable</span><strong>{item.owner}</strong></div><div><span>Próximo plazo</span><strong>{item.deadline}</strong></div><div><span>Coincidencia de origen</span><strong>{item.sourceMatch ?? "Sin coincidencia vinculada"}</strong></div><div><span>Etapa</span><select aria-label="Mover caso a etapa" onChange={(event) => onMove(event.target.value as CaseStage)} value={item.stage}>{stages.map((stage) => <option key={stage}>{stage}</option>)}</select></div></section><section className="buho-case-section"><header><h3>Tareas</h3><button type="button">Agregar</button></header><label><input defaultChecked type="checkbox" />Revisar antecedentes de la publicación</label><label><input type="checkbox" />Confirmar instrucciones con cliente</label><label><input type="checkbox" />Preparar oposición</label></section></div>{confirmingUnlink && <div aria-label="Confirmar sacar coincidencia" className="buho-case-confirmation" role="alertdialog"><div><strong>¿Estás seguro?</strong><small>La coincidencia volverá a la bandeja pendiente de revisión y el caso se mantendrá abierto.</small></div><button onClick={() => setConfirmingUnlink(false)} type="button">Cancelar</button><button className="is-danger" onClick={() => { onUnlink(); setConfirmingUnlink(false); }} type="button">Sí, sacar de caso</button></div>}<footer className="buho-drawer-actions"><button onClick={onClose} type="button">Cerrar</button>{item.sourceMatch && <button onClick={() => setConfirmingUnlink(true)} type="button">Sacar de caso</button>}{item.sourceMatch && <button onClick={() => onOpenMatch(item.sourceMatch!)} type="button">Ver coincidencia</button>}{nextStage && <button className="buho-primary" onClick={() => onMove(nextStage)} type="button">Mover a {nextStage} <span>→</span></button>}</footer></DrawerShell>;
}
function NoticeDrawer({ notice, onClose, onChange, onCopy }: { notice: Notice; onClose: () => void; onChange: (patch: Partial<Notice>) => void; onCopy: (text: string, label: string) => void }) { return <DrawerShell eyebrow={`${notice.id} · ${notice.brand}`} onClose={onClose} title="Correo prehecho" wide><div className="buho-drawer-scroll"><div className="buho-mail-context"><Tone tone={notice.urgency.toLowerCase()}>{similarityLabel(notice.urgency)}</Tone><div><strong>{notice.title}</strong><small>Destinatario sugerido: contacto del cliente</small></div></div><label className="buho-mail-field">Asunto<div><input onChange={(event) => onChange({ subject: event.target.value })} value={notice.subject} /><button onClick={() => onCopy(notice.subject, "Asunto")} type="button">Copiar asunto</button></div></label><label className="buho-mail-field">Cuerpo del correo<textarea onChange={(event) => onChange({ body: event.target.value })} rows={12} value={notice.body} /><button onClick={() => onCopy(notice.body, "Correo")} type="button">Copiar correo</button></label></div><footer className="buho-drawer-actions"><button onClick={onClose} type="button">Cerrar</button><button onClick={() => { onChange({ status: "Gestionada" }); onClose(); }} type="button">Marcar como enviado</button><button className="buho-primary" onClick={() => onCopy(notice.body, "Correo")} type="button">Copiar correo <span>→</span></button></footer></DrawerShell>; }
