"use client";
import { useState } from 'react';
import { ThumbsUp, ThumbsDown } from '@phosphor-icons/react';
import { ReviewDialog } from './review-dialog';
import type { WatchFeedbackValue } from '@/lib/watch-feedback';
export function WatchFeedback({matchId,initial}:{matchId:string;initial?:WatchFeedbackValue}){
 const [value,setValue]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[text,setText]=useState(initial?.rationale||''),[pulse,setPulse]=useState(0);
 async function save(vote:'up'|'down',rationale?:string){
  if(busy)return;setBusy(true);setError('');
  try{const response=await fetch('/api/watch/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({matchId,vote,...(rationale!==undefined?{rationale}:{})})});const payload=await response.json();if(!response.ok)throw new Error(payload.message||'No pudimos guardar tu valoración.');setValue(payload.feedback);setPulse(current=>current+1);if(rationale!==undefined)setOpen(false);}
  catch(cause){setError(cause instanceof Error?cause.message:'No pudimos guardar tu valoración.');}
  finally{setBusy(false);}
 }
 return <div className="watch-rating"><div className="watch-rating-controls"><button key={`up-${pulse}`} type="button" className={value?.vote==='up'?'is-positive':''} disabled={busy} aria-label="Esta coincidencia me interesa" aria-pressed={value?.vote==='up'} onClick={()=>void save('up')}><ThumbsUp size={21} weight={value?.vote==='up'?'fill':'regular'} aria-hidden/></button><button key={`down-${pulse}`} type="button" className={value?.vote==='down'?'is-negative':''} disabled={busy} aria-label="Esta coincidencia no me interesa" aria-pressed={value?.vote==='down'} onClick={()=>void save('down')}><ThumbsDown size={21} weight={value?.vote==='down'?'fill':'regular'} aria-hidden/></button><span>Ayúdanos a mostrarte lo que te interesa</span></div><div className="watch-rating-note">{value&&<button type="button" disabled={busy} onClick={()=>{setText(value.rationale);setOpen(true);}}>Explícanos por qué</button>}{busy?<small role="status">Guardando valoración…</small>:value&&<small role="status">{value.delivery==='sent'?'Valoración guardada y enviada':value.delivery==='waiting_search'?'Guardada · se enviará cuando se vuelva a recuperar esta coincidencia':'Guardada · envío pendiente'}</small>}{value?.delivery==='pending'&&!busy&&<button type="button" onClick={()=>void save(value.vote)}>Reintentar envío</button>}</div>{error&&<small role="alert" className="is-error">{error}</small>}{open&&value&&<ReviewDialog title="Explícanos por qué" onClose={()=>setOpen(false)} className="watch-rating-dialog"><form onSubmit={e=>{e.preventDefault();void save(value.vote,text);}}><p>Tu comentario nos ayuda a mejorar las coincidencias que te mostramos.</p><label>Motivo de tu valoración<textarea value={text} maxLength={2000} rows={5} onChange={e=>setText(e.target.value)} placeholder="¿Qué te parece relevante o poco útil de esta coincidencia?"/></label>{error&&<p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={()=>setOpen(false)}>Cancelar</button><button type="submit" className="buho-primary" disabled={busy}>{busy?'Enviando…':'Enviar comentario'}</button></footer></form></ReviewDialog>}</div>;
}
