import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { createServer } from 'node:net';
import EmbeddedPostgres from 'embedded-postgres';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import { provisionFaWorkspace, prepareIbietaPresentation, provisionPublicBriocheExample } from '../db/fa-pilot.ts';
import { verifyPassword } from '../lib/password.ts';
import { DEMO_ACTOR, DEMO_ORGANIZATION } from '../lib/tenant-context.ts';
import { prepareFaProduction, repairFaPartyOrderNotices, FA_PRODUCTION_ENVIRONMENT } from '../db/fa-production.ts';

test('pilot provisioning and one-off notification acknowledgment are isolated and idempotent', async () => {
  const listener=createServer().listen(0,'127.0.0.1');await once(listener,'listening');const port=listener.address().port;await new Promise(r=>listener.close(r));
  const directory=await mkdtemp(path.join(tmpdir(),'buho-fa-pilot-'));
  const pg=new EmbeddedPostgres({databaseDir:path.join(directory,'pg'),user:'postgres',password:'isolated',port,persistent:false,initdbFlags:['--locale=C','--encoding=UTF8'],postgresFlags:['-h','127.0.0.1'],onLog(){},onError(){}});
  let sql;
  try {
    await pg.initialise();await pg.start();await pg.createDatabase('pilot');
    const url=`postgresql://postgres:isolated@127.0.0.1:${port}/pilot`;
    const migration=postgres(url,{max:1,onnotice(){}});await migrate(drizzle(migration),{migrationsFolder:'drizzle'});await migration.end();
    sql=postgres(url,{max:1,prepare:false,onnotice(){}});
    await sql`INSERT INTO organizations(id,name,slug) VALUES (${DEMO_ORGANIZATION},'Estudio Ibieta IP','estudio-ibieta-ip')`;
    await sql`INSERT INTO users(id,name,initials) VALUES (${DEMO_ACTOR},'Ibieta','JI')`;
    await sql`INSERT INTO organization_members(organization_id,user_id,role) VALUES (${DEMO_ORGANIZATION},${DEMO_ACTOR},'admin')`;
    const fa=await provisionFaWorkspace(sql,'isolated-initial-password');assert.equal(fa.created,true);
    const [u]=await sql`SELECT password_hash,must_change_password FROM users WHERE id=${fa.userId}`;
    assert.equal(await verifyPassword('isolated-initial-password',u.password_hash),true);assert.equal(u.must_change_password,false);
    assert.equal((await provisionFaWorkspace(sql,'different-password-to-preserve')).created,false);
    assert.equal((await sql`SELECT password_hash FROM users WHERE id=${fa.userId}`)[0].password_hash,u.password_hash);
    const notice=async(org,code)=>sql`INSERT INTO notifications(organization_id,public_code,entity_type,entity_id,type,title,brand_name,urgency) VALUES (${org},${code},'organization',${org},'test','Aviso de prueba','Marca','Media')`;
    await notice(DEMO_ORGANIZATION,'OLD');await notice(fa.organizationId,'OTHER');
    assert.deepEqual(await prepareIbietaPresentation(sql),{applied:true,reviewed:1});
    assert.ok((await sql`SELECT managed_at FROM notifications WHERE public_code='OLD'`)[0].managed_at);
    assert.equal((await sql`SELECT managed_at FROM notifications WHERE public_code='OTHER'`)[0].managed_at,null);
    await notice(DEMO_ORGANIZATION,'NEW');assert.deepEqual(await prepareIbietaPresentation(sql),{applied:false,reviewed:0});
    assert.equal((await sql`SELECT managed_at FROM notifications WHERE public_code='NEW'`)[0].managed_at,null);
    assert.deepEqual(await provisionPublicBriocheExample(sql), { created: true });
    const [example] = await sql`SELECT b.monitoring_config, m.evidence, m.id FROM matches m JOIN brands b ON b.id=m.brand_id WHERE m.public_code='CO-EX-BRIOCHE-997604' AND m.organization_id=${DEMO_ORGANIZATION}`;
    assert.equal(example.monitoring_config.presentationExample,true);
    assert.equal(example.monitoring_config.monitoringEnabled,false);
    assert.equal(example.evidence.hit.score,0.7523);
    assert.equal(example.evidence.hit.history.length,19);
    assert.equal((await sql`SELECT count(*)::int AS n FROM source_snapshots WHERE organization_id=${DEMO_ORGANIZATION}`)[0].n,0);
    await sql`UPDATE matches SET review_status='Descartada' WHERE id=${example.id}`;
    assert.deepEqual(await provisionPublicBriocheExample(sql), { created: false });
    assert.equal((await sql`SELECT review_status FROM matches WHERE id=${example.id}`)[0].review_status,'Descartada');
    assert.equal((await sql`SELECT managed_at FROM notifications WHERE public_code='NEW'`)[0].managed_at,null);
    assert.equal((await sql`SELECT count(*)::int AS n FROM brands WHERE organization_id=${fa.organizationId}`)[0].n,0);
    await sql`INSERT INTO auth_sessions(token_hash,user_id,organization_id,expires_at) VALUES ('fa-session',${fa.userId},${fa.organizationId},now()+interval '1 hour'),('other-session',${DEMO_ACTOR},${DEMO_ORGANIZATION},now()+interval '1 hour')`;
    await assert.rejects(prepareFaProduction(sql,'eleven-char','dev'), /solo en production/);
    assert.deepEqual(await prepareFaProduction(sql,'eleven-char',FA_PRODUCTION_ENVIRONMENT),{applied:true,created:false});
    assert.equal(await verifyPassword('eleven-char',(await sql`SELECT password_hash FROM users WHERE id=${fa.userId}`)[0].password_hash),true);
    assert.equal((await sql`SELECT count(*)::int AS n FROM auth_sessions WHERE user_id=${fa.userId}`)[0].n,0);
    assert.equal((await sql`SELECT count(*)::int AS n FROM auth_sessions WHERE user_id=${DEMO_ACTOR}`)[0].n,1);
    assert.deepEqual(await prepareFaProduction(sql,'different-password-to-preserve',FA_PRODUCTION_ENVIRONMENT),{applied:false,created:false});
    assert.equal(await verifyPassword('eleven-char',(await sql`SELECT password_hash FROM users WHERE id=${fa.userId}`)[0].password_hash),true);
    // A fresh production database exercises creation without copying another tenant.
    const runId='6b4aacaa-bb3d-431d-8a24-69cbd8820710';
    await sql`INSERT INTO source_sync_runs(id,organization_id,trigger,status,started_at,completed_at,changed,notifications,request) VALUES (${runId},${fa.organizationId},'scheduled','success',now()-interval '1 hour',now(),89,89,'{}')`;
    const [opposition]=await sql`INSERT INTO cases(organization_id,public_code,client_name,title) VALUES (${fa.organizationId},'OR-TEST','Sin asignar','Oposición recibida') RETURNING id`;
    await sql`INSERT INTO case_tasks(organization_id,case_id,title,created_at) VALUES (${fa.organizationId},${opposition.id},'Revisar nueva actuación de la solicitud con oposición 1234567 (2026-10-01)',now()-interval '30 minutes'),(${fa.organizationId},${opposition.id},'Revisar caso inicial',now()-interval '30 minutes')`;
    await sql`UPDATE source_sync_runs SET completed_at = '2026-10-01T18:30:00.123456Z', started_at = '2026-10-01T18:00:00Z' WHERE id=${runId}`;
    await sql`UPDATE case_tasks SET created_at = '2026-10-01T18:30:00.123456Z' WHERE case_id=${opposition.id}`;
    for(let i=0;i<89;i++) await sql`INSERT INTO notifications(organization_id,public_code,entity_type,entity_id,type,title,brand_name,change_detail) VALUES (${fa.organizationId},${'ORDER-'+i},'organization',${fa.organizationId},'source','Aviso por orden','Marca',${sql.json({runId,applicationNumber:'1234567',...(i===0?{caseId:'OR-TEST'}:{}),changes:[{field:'representativeName',before:'Flores Acevedo; José Miguel Flores',after:'José Miguel Flores; Flores Acevedo'}]})})`;
    await assert.rejects(repairFaPartyOrderNotices(sql,'dev',runId),/corrida FA/);
    await sql`UPDATE notifications SET change_detail=jsonb_set(change_detail,'{changes,0,after}','"Otro representante"') WHERE public_code='ORDER-88'`;
    await assert.rejects(repairFaPartyOrderNotices(sql,FA_PRODUCTION_ENVIRONMENT,runId),/diferencias distintas/);
    assert.equal((await sql`SELECT count(*)::int AS n FROM notifications WHERE change_detail->>'invalidated'='true'`)[0].n,0);
    await sql`UPDATE notifications SET change_detail=jsonb_set(change_detail,'{changes,0,after}','"José Miguel Flores; Flores Acevedo"') WHERE public_code='ORDER-88'`;
    assert.deepEqual(await repairFaPartyOrderNotices(sql,FA_PRODUCTION_ENVIRONMENT,runId),{applied:true,invalidated:89,completedTasks:1});
    assert.equal((await sql`SELECT count(*)::int AS n FROM notifications WHERE organization_id=${fa.organizationId} AND change_detail->>'invalidated'='true'`)[0].n,89);
    assert.equal((await sql`SELECT status FROM case_tasks WHERE title='Revisar caso inicial'`)[0].status,'pending');
    assert.ok((await sql`SELECT completed_at FROM case_tasks WHERE status='completed'`)[0].completed_at);
    assert.equal((await sql`SELECT managed_at FROM notifications WHERE public_code='NEW'`)[0].managed_at,null);
    assert.deepEqual(await repairFaPartyOrderNotices(sql,FA_PRODUCTION_ENVIRONMENT,runId),{applied:false,invalidated:0,completedTasks:0});
    await pg.createDatabase('fresh_production');
    const freshUrl=`postgresql://postgres:isolated@127.0.0.1:${port}/fresh_production`;
    const freshMigration=postgres(freshUrl,{max:1,onnotice(){}});
    await migrate(drizzle(freshMigration),{migrationsFolder:'drizzle'}); await freshMigration.end();
    const fresh=postgres(freshUrl,{max:1,prepare:false,onnotice(){}});
    try {
      assert.deepEqual(await prepareFaProduction(fresh,'eleven-char',FA_PRODUCTION_ENVIRONMENT),{applied:true,created:true});
      assert.equal((await fresh`SELECT count(*)::int AS n FROM organizations`)[0].n,1);
      assert.equal((await fresh`SELECT count(*)::int AS n FROM brands`)[0].n,0);
      assert.equal(await verifyPassword('eleven-char',(await fresh`SELECT password_hash FROM users WHERE username='fa_abogados'`)[0].password_hash),true);
      assert.deepEqual(await prepareFaProduction(fresh,'different-password-to-preserve',FA_PRODUCTION_ENVIRONMENT),{applied:false,created:false});
      const [other]=await fresh`INSERT INTO organizations(name,slug) VALUES ('Other','other') RETURNING id`;
      const [faUser]=await fresh`SELECT id FROM users WHERE username='fa_abogados'`;
      await fresh`INSERT INTO organization_members(organization_id,user_id,role) VALUES (${other.id},${faUser.id},'member')`;
      await assert.rejects(prepareFaProduction(fresh,'different-password-to-preserve',FA_PRODUCTION_ENVIRONMENT), /vinculación distinta/);
    } finally {await fresh.end();}
  } finally {if(sql)await sql.end();await pg.stop();}
});
