export const NICE_CLASSES: { number: number; meaning: string }[] = [
  { number: 1, meaning: "Productos químicos para la industria, ciencia y agricultura" },
  { number: 2, meaning: "Pinturas, barnices y productos contra la corrosión" },
  { number: 3, meaning: "Cosméticos, perfumería y productos de limpieza" },
  { number: 4, meaning: "Aceites industriales, lubricantes, combustibles y velas" },
  { number: 5, meaning: "Productos farmacéuticos, médicos y veterinarios" },
  { number: 6, meaning: "Metales comunes y productos metálicos" },
  { number: 7, meaning: "Máquinas, máquinas herramienta y motores" },
  { number: 8, meaning: "Herramientas e instrumentos accionados manualmente" },
  { number: 9, meaning: "Aparatos científicos, electrónicos y software" },
  { number: 10, meaning: "Aparatos e instrumentos médicos" },
  { number: 11, meaning: "Aparatos de iluminación, calefacción, cocción y refrigeración" },
  { number: 12, meaning: "Vehículos y aparatos de transporte" },
  { number: 13, meaning: "Armas de fuego, municiones y fuegos artificiales" },
  { number: 14, meaning: "Joyería, piedras preciosas y relojería" },
  { number: 15, meaning: "Instrumentos musicales" },
  { number: 16, meaning: "Papel, impresos, material de oficina y enseñanza" },
  { number: 17, meaning: "Caucho, plásticos semielaborados y materiales aislantes" },
  { number: 18, meaning: "Cuero, equipaje, paraguas y artículos de talabartería" },
  { number: 19, meaning: "Materiales de construcción no metálicos" },
  { number: 20, meaning: "Muebles, espejos y recipientes no metálicos" },
  { number: 21, meaning: "Utensilios domésticos, recipientes, cristalería y porcelana" },
  { number: 22, meaning: "Cuerdas, redes, tiendas y materias textiles en bruto" },
  { number: 23, meaning: "Hilos e hilados para uso textil" },
  { number: 24, meaning: "Tejidos y ropa de hogar" },
  { number: 25, meaning: "Prendas de vestir, calzado y sombrerería" },
  { number: 26, meaning: "Encajes, bordados, botones y flores artificiales" },
  { number: 27, meaning: "Alfombras, revestimientos de suelos y tapices" },
  { number: 28, meaning: "Juegos, juguetes y artículos deportivos" },
  { number: 29, meaning: "Carne, pescado, lácteos y alimentos procesados" },
  { number: 30, meaning: "Café, té, cacao, pan, pastelería y condimentos" },
  { number: 31, meaning: "Productos agrícolas, plantas y animales vivos" },
  { number: 32, meaning: "Cervezas, aguas y bebidas sin alcohol" },
  { number: 33, meaning: "Bebidas alcohólicas, excepto cervezas" },
  { number: 34, meaning: "Tabaco y artículos para fumadores" },
  { number: 35, meaning: "Publicidad, gestión comercial y venta minorista" },
  { number: 36, meaning: "Servicios financieros, seguros e inmobiliarios" },
  { number: 37, meaning: "Construcción, reparación e instalación" },
  { number: 38, meaning: "Telecomunicaciones" },
  { number: 39, meaning: "Transporte, embalaje y almacenamiento" },
  { number: 40, meaning: "Tratamiento y transformación de materiales" },
  { number: 41, meaning: "Educación, formación, entretenimiento y deporte" },
  { number: 42, meaning: "Servicios científicos, tecnológicos y desarrollo de software" },
  { number: 43, meaning: "Restauración, cafeterías y alojamiento temporal" },
  { number: 44, meaning: "Servicios médicos, veterinarios, agrícolas y de belleza" },
  { number: 45, meaning: "Servicios jurídicos, seguridad y servicios personales" },
];
