import type { RegistrationApplication } from "./registration-data";

/** Fixed reference date for the educational examples; these records never enter the client portfolio. */
export const PROCESS_DEMO_DATE = "2026-09-07";

type ScenarioInput = Pick<RegistrationApplication, "name" | "filedAt" | "statusId" | "recentEvent" | "demoScenario" | "history"> & Partial<RegistrationApplication>;

function scenario(number: number, input: ScenarioInput): RegistrationApplication {
  const reference = `DEMO-${String(number).padStart(3, "0")}`;
  return {
    id: reference,
    applicationNumber: reference,
    type: "Denominativa",
    niceClasses: "35",
    holderRut: "No aplica · ejemplo",
    holder: `${input.name} · titular ficticio`,
    client: "Cartera de demostración",
    ...input,
  };
}

/** Entirely simulated procedural examples. Dates, acts, parties and identifiers are fictitious. */
export const PROCESS_SCENARIOS: RegistrationApplication[] = [
  scenario(1, {
    name: "ALBOR DE EJEMPLO",
    filedAt: "2026-09-02",
    statusId: "inapi-waiting",
    niceClasses: "9 y 42",
    recentEvent: "Solicitud presentada; examen de forma pendiente",
    demoScenario: "Presentación y examen formal. El ingreso no abre por sí solo un plazo de respuesta ni la oposición.",
    history: [
      { date: "2026-09-02", intake: true, detail: "Ejemplo: solicitud de marca denominativa y cobertura de productos y servicios presentada." },
      { date: "2026-09-03", status: "Examen de forma pendiente", detail: "Aún no consta observación ni aceptación a trámite." },
    ],
  }),
  scenario(2, {
    name: "TRAZO DE EJEMPLO",
    filedAt: "2026-08-17",
    statusId: "form-observation",
    recentEvent: "Observación de forma notificada; respuesta pendiente",
    demoScenario: "Observación formal con notificación identificada. La respuesta tiene 30 días hábiles; el plazo no nace de la presentación inicial.",
    procedure: {
      sourceActDate: "2026-08-26",
      sourceActDescription: "Resolución de observación de forma, notificada el 27 de agosto de 2026 (ejemplo).",
      notifiedAt: "2026-08-27",
    },
    history: [
      { date: "2026-08-17", intake: true },
      { date: "2026-08-26", status: "Observación de forma", detail: "Se requiere precisar servicios de la clase 35 y acreditar representación." },
      { date: "2026-08-27", status: "Notificación de observación de forma", detail: "Notificación identificada en este supuesto simulado; comienza el plazo para responder." },
    ],
  }),
  scenario(3, {
    name: "LÍNEA DE EJEMPLO",
    filedAt: "2026-07-20",
    statusId: "form-observation",
    recentEvent: "Cumplimiento de observación presentado; pendiente de proveer",
    demoScenario: "Responder una observación no equivale a que INAPI la tenga por subsanada. La gestión fue presentada y espera pronunciamiento.",
    procedure: {
      sourceActDate: "2026-08-04",
      sourceActDescription: "Observación de forma notificada el 5 de agosto; cumplimiento presentado el 21 de agosto (ejemplo).",
      notifiedAt: "2026-08-05",
      responseFiledAt: "2026-08-21",
    },
    history: [
      { date: "2026-07-20", intake: true },
      { date: "2026-08-05", status: "Observación de forma notificada", detail: "Se requiere acompañar poder suficiente." },
      { date: "2026-08-21", status: "Cumplimiento presentado", detail: "Se acompaña poder. INAPI aún debe pronunciarse sobre la suficiencia del cumplimiento." },
    ],
  }),
  scenario(4, {
    name: "UMBRAL DE EJEMPLO",
    filedAt: "2026-08-10",
    statusId: "accepted-publication",
    niceClasses: "30 y 43",
    recentEvent: "Aceptación a trámite notificada; requerimiento de publicación pendiente",
    demoScenario: "Antes de publicar puede existir un plazo: 20 días hábiles para requerir y pagar la publicación desde la notificación de aceptación. Todavía no se abre la oposición.",
    procedure: {
      sourceActDate: "2026-08-31",
      sourceActDescription: "Aceptación a trámite notificada el 1 de septiembre de 2026 (ejemplo).",
      notifiedAt: "2026-09-01",
    },
    history: [
      { date: "2026-08-10", intake: true },
      { date: "2026-08-31", status: "Aceptación a trámite", detail: "El examen de forma no formula reparos pendientes." },
      { date: "2026-09-01", status: "Notificación de aceptación a trámite", detail: "Debe requerirse y pagarse la publicación dentro del plazo aplicable. No consta publicación efectiva." },
    ],
  }),
  scenario(5, {
    name: "PÁGINA DE EJEMPLO",
    filedAt: "2026-08-03",
    statusId: "publication-pending",
    recentEvent: "Publicación requerida y pagada; esperando edición del Diario Oficial",
    demoScenario: "La gestión de requerir y pagar ya se cumplió. La fecha de pago no se usa como publicación ni como inicio de oposición.",
    procedure: {
      notifiedAt: "2026-08-24",
      publicationRequestedAt: "2026-08-28",
      sourceActDate: "2026-08-28",
      sourceActDescription: "Requerimiento y pago de publicación acreditados el 28 de agosto (ejemplo).",
    },
    history: [
      { date: "2026-08-03", intake: true },
      { date: "2026-08-24", status: "Aceptación a trámite notificada" },
      { date: "2026-08-28", status: "Publicación requerida y pagada", detail: "Gestión efectuada dentro del plazo. Se espera la publicación efectiva del extracto." },
    ],
  }),
  scenario(6, {
    name: "RAMA DE EJEMPLO",
    filedAt: "2026-06-01",
    statusId: "not-filed",
    recentEvent: "INAPI tuvo la solicitud por no presentada",
    demoScenario: "La falta de requerimiento de publicación terminó en una resolución expresa. El sistema no deduce este resultado sólo porque pasó una fecha.",
    procedure: { sourceActDate: "2026-08-10", sourceActDescription: "Resolución que tiene la solicitud por no presentada por falta de requerimiento de publicación (ejemplo)." },
    history: [
      { date: "2026-06-01", intake: true },
      { date: "2026-07-01", status: "Aceptación a trámite notificada", detail: "Se abre plazo para requerir y pagar la publicación." },
      { date: "2026-08-10", status: "Solicitud tenida por no presentada", detail: "Consta resolución expresa por no haber requerido la publicación dentro del plazo." },
    ],
  }),
  scenario(7, {
    name: "FARO DE EJEMPLO",
    filedAt: "2026-07-06",
    statusId: "opposition-window",
    publishedAt: "2026-08-31",
    recentEvent: "Extracto publicado en Diario Oficial; plazo de oposición abierto",
    demoScenario: "La publicación efectiva es el hito que activa los 30 días hábiles para deducir oposición. Requerimiento, pago y publicación conservan fechas distintas.",
    procedure: { publicationRequestedAt: "2026-08-14", sourceActDate: "2026-08-31", sourceActDescription: "Publicación efectiva del extracto en Diario Oficial (ejemplo)." },
    history: [
      { date: "2026-07-06", intake: true },
      { date: "2026-08-10", status: "Aceptación a trámite notificada" },
      { date: "2026-08-14", status: "Publicación requerida y pagada" },
      { date: "2026-08-31", status: "Publicación en Diario Oficial", detail: "Comienza el plazo de oposición de terceros." },
    ],
  }),
  scenario(8, {
    name: "ENLACE DE EJEMPLO",
    filedAt: "2026-04-06",
    statusId: "opposition-answer",
    publishedAt: "2026-06-15",
    recentEvent: "Traslado de oposición notificado en casilla electrónica",
    demoScenario: "La contestación tiene su propio plazo de 30 días hábiles desde la notificación del traslado. La presentación de la oposición y su traslado no son el mismo hito.",
    procedure: { notifiedAt: "2026-08-24", sourceActDate: "2026-08-21", sourceActDescription: "Traslado de oposición depositado en casilla electrónica el 24 de agosto (ejemplo)." },
    history: [
      { date: "2026-04-06", intake: true },
      { date: "2026-06-15", status: "Publicación en Diario Oficial" },
      { date: "2026-07-10", status: "Oposición presentada", detail: "Un tercero, representado por abogado, invoca derechos marcarios anteriores." },
      { date: "2026-08-24", status: "Traslado de oposición notificado", detail: "Notificación mediante depósito en casilla electrónica. Contestación pendiente, con patrocinio de abogado." },
    ],
  }),
  scenario(9, {
    name: "TELAR DE EJEMPLO",
    filedAt: "2026-02-02",
    statusId: "evidence-period",
    niceClasses: "24 y 25",
    publishedAt: "2026-03-16",
    recentEvent: "Causa recibida a prueba; término probatorio abierto",
    demoScenario: "La prueba se abre por resolución cuando existen hechos sustanciales, pertinentes y controvertidos. No se agrega como etapa automática a toda oposición.",
    procedure: { notifiedAt: "2026-08-17", sourceActDate: "2026-08-14", sourceActDescription: "Resolución que recibe la causa a prueba, notificada por estado diario el 17 de agosto (ejemplo)." },
    history: [
      { date: "2026-02-02", intake: true },
      { date: "2026-03-16", status: "Publicación en Diario Oficial" },
      { date: "2026-04-08", status: "Oposición presentada" },
      { date: "2026-05-18", status: "Traslado de oposición notificado" },
      { date: "2026-06-08", status: "Contestación presentada", detail: "El solicitante controvierte los hechos que sustentan la oposición." },
      { date: "2026-08-17", status: "Resolución de prueba notificada", detail: "Se fijan hechos a probar. Término probatorio de 30 días hábiles." },
    ],
  }),
  scenario(10, {
    name: "TRAMA DE EJEMPLO",
    filedAt: "2026-01-12",
    statusId: "evidence-period",
    publishedAt: "2026-03-02",
    recentEvent: "Prórroga de término probatorio concedida por 20 días hábiles",
    demoScenario: "Una prórroga requiere solicitud oportuna y concesión expresa. Este ejemplo suma sólo los 20 días concedidos, dentro del máximo adicional de 30.",
    procedure: { notifiedAt: "2026-07-06", evidenceExtensionDays: 20, sourceActDate: "2026-08-05", sourceActDescription: "Prórroga de 20 días hábiles concedida expresamente; término original notificado el 6 de julio (ejemplo)." },
    history: [
      { date: "2026-01-12", intake: true },
      { date: "2026-03-02", status: "Publicación en Diario Oficial" },
      { date: "2026-03-25", status: "Oposición presentada" },
      { date: "2026-04-20", status: "Traslado de oposición notificado" },
      { date: "2026-05-11", status: "Contestación presentada" },
      { date: "2026-07-06", status: "Resolución de prueba notificada", detail: "Término probatorio original de 30 días hábiles." },
      { date: "2026-07-31", status: "Prórroga solicitada", detail: "Solicitud fundada presentada antes del vencimiento del término original." },
      { date: "2026-08-05", status: "Prórroga concedida", detail: "Resolución concede 20 días hábiles adicionales. No se aplica la extensión máxima automáticamente." },
    ],
  }),
  scenario(11, {
    name: "ACUERDO DE EJEMPLO",
    filedAt: "2026-01-05",
    statusId: "decision-pending",
    publishedAt: "2026-02-16",
    recentEvent: "Autos para fallo; oposición pendiente de resolución",
    demoScenario: "La oposición puede llegar a fallo sin apertura de prueba. La contestación y los argumentos de las partes no permiten anticipar concesión o rechazo.",
    procedure: { sourceActDate: "2026-08-31", sourceActDescription: "Autos para fallo sin apertura de término probatorio (ejemplo)." },
    history: [
      { date: "2026-01-05", intake: true },
      { date: "2026-02-16", status: "Publicación en Diario Oficial" },
      { date: "2026-03-09", status: "Oposición presentada" },
      { date: "2026-04-13", status: "Traslado de oposición notificado" },
      { date: "2026-05-04", status: "Contestación presentada", detail: "La controversia se circunscribe a cuestiones de derecho." },
      { date: "2026-08-31", status: "Autos para fallo", detail: "No se abrió término probatorio. Pendiente de decisión de INAPI." },
    ],
  }),
  scenario(12, {
    name: "CAUCE DE EJEMPLO",
    filedAt: "2026-03-02",
    statusId: "substantive-exam",
    publishedAt: "2026-05-18",
    recentEvent: "Examen de fondo en curso; sin actuación de respuesta pendiente",
    demoScenario: "Aunque no exista oposición, INAPI examina las prohibiciones de registro. La etapa no tiene una fecha de resolución fijada en este ejemplo.",
    history: [
      { date: "2026-03-02", intake: true },
      { date: "2026-05-18", status: "Publicación en Diario Oficial" },
      { date: "2026-07-06", status: "Examen de fondo", detail: "El expediente informa ausencia de oposiciones. Se examinan prohibiciones absolutas y relativas de registro." },
    ],
  }),
  scenario(13, {
    name: "MATIZ DE EJEMPLO",
    filedAt: "2026-01-19",
    statusId: "substantive-objection",
    publishedAt: "2026-03-30",
    recentEvent: "Plazo de respuesta a observación de fondo transcurrido; resolución pendiente",
    demoScenario: "El plazo de 30 días hábiles transcurrió sin respuesta registrada. Se conserva la observación pendiente: la aplicación no inventa un rechazo ni un abandono.",
    procedure: { notifiedAt: "2026-06-15", sourceActDate: "2026-06-12", sourceActDescription: "Observación de fondo depositada en casilla electrónica el 15 de junio; no consta pronunciamiento posterior (ejemplo)." },
    history: [
      { date: "2026-01-19", intake: true },
      { date: "2026-03-30", status: "Publicación en Diario Oficial" },
      { date: "2026-05-18", status: "Examen de fondo" },
      { date: "2026-06-15", status: "Observación de fondo notificada", detail: "Se objeta falta de distintividad respecto de parte de la cobertura solicitada. No consta respuesta ni resolución final posterior." },
    ],
  }),
  scenario(14, {
    name: "NEXO DE EJEMPLO",
    filedAt: "2026-04-13",
    statusId: "opposition-answer",
    niceClasses: "9 y 42",
    publishedAt: "2026-06-22",
    recentEvent: "Traslado de oposición y observación de fondo notificados conjuntamente",
    demoScenario: "Oposición y examen de fondo pueden coexistir. El supuesto conserva dos gestiones de respuesta y sus respectivos activadores, aunque coincidan en fecha.",
    procedure: {
      notifiedAt: "2026-08-24",
      sourceActDate: "2026-08-21",
      sourceActDescription: "Notificación conjunta en casilla electrónica de traslado de oposición y observación de fondo (ejemplo).",
      concurrent: [{ statusId: "substantive-objection", notifiedAt: "2026-08-24", sourceActDate: "2026-08-21" }],
    },
    history: [
      { date: "2026-04-13", intake: true },
      { date: "2026-06-22", status: "Publicación en Diario Oficial" },
      { date: "2026-07-17", status: "Oposición presentada", detail: "Un tercero invoca semejanza con una marca anterior para servicios relacionados." },
      { date: "2026-08-24", status: "Traslado de oposición y observación de fondo notificados", detail: "INAPI también formula observación de fondo. La defensa debe abordar ambos fundamentos; cada gestión se conserva en el seguimiento." },
    ],
  }),
  scenario(15, {
    name: "HORIZONTE DE EJEMPLO",
    filedAt: "2026-02-09",
    statusId: "finality-pending",
    publishedAt: "2026-04-20",
    recentEvent: "Resolución de aceptación a registro; ejecutoria aún no informada",
    demoScenario: "Aceptación a registro y ejecutoria son hitos distintos. Los 60 días hábiles para pago y acreditación final no se calculan desde la sola aceptación.",
    procedure: { notifiedAt: "2026-09-02", sourceActDate: "2026-09-01", sourceActDescription: "Aceptación a registro notificada; aún no consta ejecutoria (ejemplo)." },
    history: [
      { date: "2026-02-09", intake: true },
      { date: "2026-04-20", status: "Publicación en Diario Oficial" },
      { date: "2026-06-08", status: "Examen de fondo" },
      { date: "2026-09-02", status: "Aceptación a registro notificada", detail: "Aceptación total de la cobertura. No consta ejecutoria, pago final ni número de registro." },
    ],
  }),
  scenario(16, {
    name: "FRONDA DE EJEMPLO",
    filedAt: "2026-01-26",
    statusId: "partial-appeal",
    niceClasses: "30 y 35",
    publishedAt: "2026-03-23",
    recentEvent: "Aceptación parcial notificada; plazo de apelación abierto",
    demoScenario: "Una aceptación parcial puede limitar productos o servicios dentro de una misma clase. La parte denegada puede impugnarse dentro del plazo aplicable; no se presume aceptación total.",
    procedure: { notifiedAt: "2026-09-01", sourceActDate: "2026-08-31", sourceActDescription: "Resolución de aceptación parcial notificada el 1 de septiembre (ejemplo)." },
    history: [
      { date: "2026-01-26", intake: true },
      { date: "2026-03-23", status: "Publicación en Diario Oficial" },
      { date: "2026-05-11", status: "Examen de fondo" },
      { date: "2026-06-01", status: "Observación de fondo notificada" },
      { date: "2026-06-22", status: "Respuesta a observación de fondo presentada" },
      { date: "2026-09-01", status: "Aceptación parcial notificada", detail: "Se aceptan café e infusiones de clase 30 y servicios de clase 35; se rechazan preparaciones de cacao de clase 30. Plazo de apelación de 15 días hábiles." },
    ],
  }),
  scenario(17, {
    name: "PRISMA DE EJEMPLO",
    filedAt: "2026-01-05",
    statusId: "appeal-pending",
    publishedAt: "2026-02-16",
    recentEvent: "Apelación concedida; expediente ante el Tribunal de Propiedad Industrial",
    demoScenario: "La apelación presentada oportunamente y concedida en ambos efectos mantiene pendiente el resultado. Una eventual sentencia del tribunal tampoco acredita por sí sola la ejecutoria.",
    procedure: { sourceActDate: "2026-08-24", sourceActDescription: "Apelación concedida en ambos efectos y remitida al Tribunal de Propiedad Industrial (ejemplo)." },
    history: [
      { date: "2026-01-05", intake: true },
      { date: "2026-02-16", status: "Publicación en Diario Oficial" },
      { date: "2026-04-06", status: "Observación de fondo notificada" },
      { date: "2026-04-27", status: "Respuesta presentada" },
      { date: "2026-08-03", status: "Rechazo notificado" },
      { date: "2026-08-14", status: "Apelación interpuesta", detail: "Recurso presentado ante INAPI para conocimiento del Tribunal de Propiedad Industrial, dentro del plazo." },
      { date: "2026-08-24", status: "Apelación concedida en ambos efectos", detail: "Tramitación ante el Tribunal de Propiedad Industrial. No se presume rechazo firme ni nace un plazo de pago final." },
    ],
  }),
  scenario(18, {
    name: "CIMA DE EJEMPLO",
    filedAt: "2026-01-12",
    statusId: "accepted-payment",
    publishedAt: "2026-03-09",
    recentEvent: "Aceptación ejecutoriada; pago y acreditación de derechos finales pendientes",
    demoScenario: "La ejecutoria identificada activa los 60 días hábiles para pagar y acreditar derechos finales. Aún no existe registro concedido.",
    procedure: { finalAt: "2026-08-24", sourceActDate: "2026-08-24", sourceActDescription: "Constancia de ejecutoria de la resolución que autoriza inscripción (ejemplo)." },
    history: [
      { date: "2026-01-12", intake: true },
      { date: "2026-03-09", status: "Publicación en Diario Oficial" },
      { date: "2026-04-27", status: "Examen de fondo" },
      { date: "2026-07-27", status: "Aceptación a registro notificada" },
      { date: "2026-08-24", status: "Aceptación ejecutoriada", detail: "Consta ejecutoria. Se abre plazo de 60 días hábiles para pagar y acreditar los derechos finales." },
    ],
  }),
  scenario(19, {
    name: "HUELLA DE EJEMPLO",
    filedAt: "2026-01-19",
    statusId: "payment-verification",
    publishedAt: "2026-03-16",
    recentEvent: "Pago final acreditado; registro aún no asignado",
    demoScenario: "Pago, acreditación y concesión conservan hitos propios. La acreditación oportuna permite esperar el registro sin presentarlo como ya concedido.",
    procedure: { finalAt: "2026-08-10", paymentAccreditedAt: "2026-08-31", sourceActDate: "2026-08-31", sourceActDescription: "Comprobante de pago final acreditado en el expediente (ejemplo)." },
    history: [
      { date: "2026-01-19", intake: true },
      { date: "2026-03-16", status: "Publicación en Diario Oficial" },
      { date: "2026-05-04", status: "Examen de fondo" },
      { date: "2026-07-13", status: "Aceptación a registro notificada" },
      { date: "2026-08-10", status: "Aceptación ejecutoriada" },
      { date: "2026-08-31", status: "Pago final acreditado", detail: "Comprobante incorporado oportunamente al expediente. Pendiente de verificación y asignación del registro." },
    ],
  }),
  scenario(20, {
    name: "RAÍZ DE EJEMPLO",
    filedAt: "2026-01-05",
    statusId: "registered",
    publishedAt: "2026-02-16",
    registrationNumber: "DEMO-REG-020",
    registrationDate: "2026-08-31",
    expirationDate: "2036-08-31",
    recentEvent: "Registro concedido; vigencia informada desde la inscripción",
    demoScenario: "La vigencia de 10 años se cuenta desde la inscripción, no desde solicitud, publicación, aceptación o pago. Número y fechas de este ejemplo son ficticios.",
    procedure: { finalAt: "2026-07-20", paymentAccreditedAt: "2026-08-03", sourceActDate: "2026-08-31", sourceActDescription: "Inscripción y asignación del registro de demostración (ejemplo)." },
    history: [
      { date: "2026-01-05", intake: true },
      { date: "2026-02-16", status: "Publicación en Diario Oficial" },
      { date: "2026-04-06", status: "Examen de fondo" },
      { date: "2026-06-22", status: "Aceptación a registro notificada" },
      { date: "2026-07-20", status: "Aceptación ejecutoriada" },
      { date: "2026-08-03", status: "Pago final acreditado" },
      { date: "2026-08-31", status: "Registro concedido", detail: "Registro ficticio DEMO-REG-020. Inscripción: 31 de agosto de 2026; vencimiento de vigencia: 31 de agosto de 2036." },
    ],
  }),
  scenario(21, {
    name: "CONTORNO DE EJEMPLO",
    filedAt: "2026-01-12",
    statusId: "rejected-final",
    publishedAt: "2026-03-02",
    recentEvent: "Rechazo firme informado en el expediente",
    demoScenario: "El cierre se muestra porque existe constancia de rechazo firme. Una observación, oposición o rechazo recurrible no produce este estado automáticamente.",
    procedure: { finalAt: "2026-08-31", sourceActDate: "2026-08-31", sourceActDescription: "Constancia de ejecutoria del rechazo y archivo del expediente (ejemplo)." },
    history: [
      { date: "2026-01-12", intake: true },
      { date: "2026-03-02", status: "Publicación en Diario Oficial" },
      { date: "2026-04-20", status: "Observación de fondo notificada" },
      { date: "2026-05-11", status: "Respuesta a observación presentada" },
      { date: "2026-08-03", status: "Rechazo notificado", detail: "INAPI mantiene la causal de irregistrabilidad. Se abre el plazo de impugnación aplicable." },
      { date: "2026-08-31", status: "Rechazo firme", detail: "Consta ejecutoria del rechazo y archivo. No se infiere firmeza de la mera ausencia de actuaciones visibles." },
    ],
  }),
  scenario(22, {
    name: "SENDERO DE EJEMPLO",
    filedAt: "2025-10-06",
    statusId: "abandoned-payment",
    publishedAt: "2025-12-01",
    recentEvent: "Abandono declarado por falta de pago y acreditación final",
    demoScenario: "La solicitud fue aceptada, pero no llegó a registro. Una resolución posterior declara abandono por no cumplir el pago y la acreditación de derechos finales.",
    procedure: { finalAt: "2026-04-06", sourceActDate: "2026-08-17", sourceActDescription: "Resolución expresa de abandono por falta de pago y acreditación de derechos finales (ejemplo)." },
    history: [
      { date: "2025-10-06", intake: true },
      { date: "2025-12-01", status: "Publicación en Diario Oficial" },
      { date: "2026-01-19", status: "Examen de fondo" },
      { date: "2026-03-02", status: "Aceptación a registro notificada" },
      { date: "2026-04-06", status: "Aceptación ejecutoriada", detail: "Comienza el plazo para pagar y acreditar derechos finales." },
      { date: "2026-08-17", status: "Abandono declarado", detail: "Resolución expresa constata incumplimiento del pago y la acreditación dentro del plazo y ordena el archivo." },
    ],
  }),
];
