export const APP_VERSION = "1.0";
export const RELEASE_INCLUDED = [
  "Actualizaciones de pantalla solo cuando cambian los datos, vigilancia paginada y consultas suspendidas en pestañas ocultas. Daniel conserva la revisión diaria y Búho se actualiza a pedido.",
  "Mis marcas reúne registros y solicitudes propias; Vigilancia separa Por revisar y En seguimiento. Rangos de alta y media similitud configurables por organización.",
  "Aviso interno al publicarse en Diario Oficial, comparación de marcas lado a lado y factibilidad con imagen removible y estados coloreados.",
  "Vigilancia real de marcas propias y solicitudes: 50 similitudes por consulta, con exclusión local de Denegada, Desistida y Abandonada; cinco visibles y Buscar más de cinco en cinco.",
  "Seguimiento individual persistente, logos y coberturas reales, estado INAPI e historial; las nuevas revisiones conservan decisiones y casos.",
  "Revisiones diarias en segundo plano, detección de ingreso y publicación, reintentos y recuperación sin duplicar coincidencias.",
  "Factibilidad real por nombre e imagen, con agrupación inicial por titular, fechas de solicitud/publicación/registro y opciones de coincidencia textual sobre los candidatos recuperados.",
  "Acceso con usuario y clave, cambio de clave temporal y espacios independientes por organización.",
  "Búsqueda de cartera por marca, solicitud, nombre, razón social y RUT de titular o representante. Excel y CSV admiten esos datos; se explican candidatos y se confirma cliente y rol antes de incorporar sin duplicados.",
  "Oposiciones presentadas: expediente contrario en Casos, marca de fundamento opcional, historial y nuevas actuaciones con aviso y tarea de revisión.",
  "Solicitudes de registro: tarjetas predeterminadas, lista y calendario, con estado procesal, último hito relevante y contexto del plazo.",
  "Accesos directos desde ambos resúmenes a sus calendarios completos. Calendarios de Casos y Solicitudes con mes, semana, próxima semana, tareas por día y lista inferior por categoría.",
  "Tareas persistentes con prioridad alta, media o baja, fecha, responsable y autoasignación. Filtro por prioridad de tareas pendientes y confirmación al eliminar.",
  "Casos con modo simple inicial y modo detallado para tablero, lista y calendario; prioridad editable desde la ficha y expediente de la marca defendida presentado en tabla.",
  "Clientes con acceso directo a marcas y solicitudes vinculadas, e informes de cartera en Excel, Word o PDF con selección individual de columnas y todos los datos guardados disponibles.",
  "Alertas de tareas y plazos visibles desde todos los módulos.",
  "Notificaciones con eliminación individual y limpieza de Prioritarias o Todas, persistentes por espacio. Las tareas pueden eliminarse desde las agendas y desde su editor.",
  "Búsqueda general por marca, cliente, RUT, solicitud, registro, representante o contraparte, con resultados enlazados a sus fichas. Mis marcas comienza con solicitud y muestra estado y pendientes como texto.",
  "Paneles de detalle que se cierran al pulsar fuera; informes de prefactibilidad renombrados a informes de factibilidad.",
  "Plazos vinculados a su actuación y notificación acreditada: la fecha de una resolución no se sustituye automáticamente por una fecha de notificación ni de firmeza.",
  "Correo al cliente con cuadro comparativo copiable y firma de la sesión. El PDF de demostración se oculta en coincidencias reales.",
  "Seguimiento INAPI, historial de actuaciones y los 22 ejemplos del procedimiento de la versión anterior.",
];
export const RELEASE_UPCOMING = [
  { title: "Servidor dedicado para ampliar la vigilancia", items: ["Instalar el sistema en un servidor dedicado para revisar más solicitudes y controlar el costo de operación.", "Medir capacidad, memoria, tiempos, respaldos y recuperación; coordinar con DeQuiénEs las cuotas y concurrencia antes de aumentar el volumen de búsquedas."] },
  { title: "Filtro de estados para vigilancia", items: ["Víctor incorporará el filtro por estado a la llamada de búsqueda; todavía no está disponible. La interfaz oculta Denegada, Desistida y Abandonada, pero falta el filtro previo en la API.", "Falta acordar el catálogo exacto de estados. No asumir que una etiqueta de rechazo siempre significa que el proceso terminó definitivamente: podría haber recursos o instancias posteriores."] },
  { title: "Calidad y cobertura de las búsquedas", items: ["Calibrar la relevancia y los niveles con revisión experta, sin interpretar el puntaje de ordenamiento como probabilidad jurídica.", "Confirmar límites, paginación y datos incorporados tarde. El stock de 50 y las ventanas de novedades son conjuntos acotados, no una garantía de exhaustividad.", "Confirmar con Víctor la disponibilidad diaria, cuotas, rendimiento y alcance semántico. Hay señales visuales y fonéticas reales."] },
  { title: "Correos al abogado con Resend", items: ["Recordatorios de tareas y plazos antes del vencimiento, con fecha, responsable y enlace al expediente.", "Aviso específico cuando INAPI emita el título o certificado de titularidad.", "Evitar duplicados y cancelar recordatorios cuando cambie el plazo, se complete la tarea o concluya el caso; registrar entrega, errores y reintentos."] },
  { title: "Integración con el Tribunal de Propiedad Industrial (TPI / TDPI)", items: ["Detectar el ingreso de la apelación al tribunal, además de su aparición en tabla.", "Seguir las actuaciones de alegatos y adhesión conforme a su resolución y regla aplicable. No crear una obligación general de hacerse parte ni un plazo automático de cinco días desde el ingreso al TDPI."] },
  { title: "Validación de búsquedas fonéticas", items: ["Detectar términos o segmentos clave dentro de denominaciones extensas, aunque reduzcan la similitud global. Incluir casos de marcas muy cortas y de dos letras en la validación del motor."] },
  { title: "Ampliar la búsqueda de expedientes", items: ["Consulta directa por número de registro cuando la fuente la documente; hoy la consulta exacta usa número de solicitud.", "Autocompletar nombres y titulares y conservar búsquedas para retomarlas.", "Ampliar el descubrimiento de carteras por imagen y descripción. La búsqueda por nombre, solicitud, titular, representante y RUT ya está disponible."] },
  { title: "Patentes", items: ["Vigilancia de patentes dentro del módulo de Vigilancia.", "Seguimiento internacional de patentes PCT por jurisdicción, anualidades y corresponsales."] },
  { title: "Gestión de casos para reemplazar Trello", items: ["Completar comentarios, documentos, checklists y colaboración según los flujos del estudio, sobre las tareas y fechas ya disponibles."] },
  { title: "Otros desarrollos pendientes", items: ["Guardar estudios de prefactibilidad e imágenes por organización, con acceso y retención definidos.", "Generar PDF técnico específico por vigilancia y almacenar archivos con acceso apropiado.", "Validación Niza/Madrid y calendario legal plurianual.", "Invitaciones de equipo, recuperación de claves y operación productiva."] },
];
